"""Phase 11.3 — the one canonical application gateway.

``ApplicationGateway`` is the single transport-neutral public entrypoint of the
CMM OS application backend.  Every public request — HTTP, CLI or in-process —
enters here and nowhere else.  There is deliberately no second entrypoint name:
an ``ApplicationBackend``, ``BackendService`` or ``ApplicationFacade`` would be
a parallel owner of the same boundary.

The gateway owns exactly four decisions:

- **role and version** — an ``ApplicationQuery`` may carry only a query
  operation, an ``ApplicationCommand`` only a command operation, and a request
  with no declared role fails closed.  A tampered API version fails closed as
  ``UNSUPPORTED_VERSION`` rather than being served;
- **explicit dispatch** — the six frozen operations are dispatched through an
  explicit branch.  There is no handler registry, no import-by-string and no
  reflection, so an unknown or future operation can never be reached by a
  string a caller controls;
- **idempotency at the public command boundary** — a keyed command is replayed
  from the stored safe response when the fingerprint matches, rejected as
  ``IDEMPOTENCY_CONFLICT`` when it does not, and recorded only after a terminal
  safe response exists.  A response synthesized by the failure handler is never
  recorded, so an internal defect can not be pinned to a caller's key.  The
  complete keyed ``get -> execute -> put`` sequence is one atomic critical
  section for this gateway instance, so two simultaneous keyed commands of one
  key can not both observe an absent record and both enter the canonical owner;
- **fail-closed failure** — no exception escapes ``handle()`` for an accepted
  request.  Every failure becomes ``failed_response(...)`` built from the safe
  :func:`~cmm.application.errors.safe_error_from_exception` projection, so an
  exception message, a traceback, a path or a credential can never reach a
  public response.

The gateway resolves no domain, selects no agent, routes no model, executes no
workflow and mutates no session itself: it validates, dispatches and normalizes.
Cancellation is reported honestly as ``CAPABILITY_UNAVAILABLE`` because Phase
11.3 introduces no cancellable-request runtime and no fake cancellation
registry.

See ``docs/reference/phase-11-application-backend.md``.
"""

from __future__ import annotations

from collections.abc import Mapping
from threading import Lock
from typing import Any
from uuid import uuid4

from cmm.application.capabilities import CapabilityApplicationService
from cmm.application.contracts import (
    APPLICATION_API_VERSION,
    COMMAND_OPERATIONS,
    QUERY_OPERATIONS,
    ApplicationCommand,
    ApplicationError,
    ApplicationErrorCode,
    ApplicationMessage,
    ApplicationOperation,
    ApplicationQuery,
    ApplicationRequest,
    ApplicationResponse,
    ApplicationStatus,
)
from cmm.application.errors import (
    IdempotencyConflictError,
    InvalidApplicationRequestError,
    UnsupportedApplicationVersionError,
    failed_response,
    safe_error_from_exception,
)
from cmm.application.health import HealthApplicationService
from cmm.application.idempotency import (
    IdempotencyRecord,
    InMemoryIdempotencyRepository,
    fingerprint_command,
)
from cmm.application.requests import RequestApplicationService
from cmm.application.sessions import SessionApplicationService

__all__ = ["CANCELLATION_UNAVAILABLE_MESSAGE", "ApplicationGateway"]

#: The frozen safe public message for the unavailable cancellation surface.
CANCELLATION_UNAVAILABLE_MESSAGE = (
    "Request cancellation is not available for the current execution boundary"
)

#: The public commands that opt into repeatable replay when a key is supplied.
_IDEMPOTENT_OPERATIONS = frozenset(
    {
        ApplicationOperation.SESSION_CREATE,
        ApplicationOperation.MESSAGE_SUBMIT,
    }
)

#: The default public content type of a submitted message.
_DEFAULT_CONTENT_TYPE = "text/plain"


def _success_response(request_id: str, data: Mapping[str, Any]) -> ApplicationResponse:
    """Return one successful, versioned public response envelope."""

    return ApplicationResponse(
        request_id=request_id,
        api_version=APPLICATION_API_VERSION,
        status=ApplicationStatus.SUCCESS,
        data=data,
        error=None,
        metadata={},
    )


def _session_id_from_payload(payload: Mapping[str, Any]) -> str:
    """Return the requested session identifier, or a fresh UUID4.

    An absent identifier is generated by the application layer; a present but
    non-textual one is malformed public input and fails closed.
    """

    candidate = payload.get("session_id")
    if candidate is None:
        return str(uuid4())
    if not isinstance(candidate, str):
        raise InvalidApplicationRequestError(
            details={"reason_code": "INVALID_SESSION_ID"}
        )
    return candidate


def _message_from_request(request: ApplicationRequest) -> ApplicationMessage:
    """Adapt one public message request into the public message contract."""

    actor_id = request.actor_id
    if actor_id is None:
        raise InvalidApplicationRequestError(
            details={"reason_code": "MISSING_ACTOR_ID"}
        )

    session_id = request.session_id
    if session_id is None:
        raise InvalidApplicationRequestError(
            details={"reason_code": "MISSING_SESSION_ID"}
        )

    message_id = request.payload.get("message_id")
    if not isinstance(message_id, str) or not message_id.strip():
        raise InvalidApplicationRequestError(
            details={"reason_code": "INVALID_MESSAGE_ID"}
        )

    expected_session_revision = None
    idempotency_key = None
    if isinstance(request, ApplicationCommand):
        expected_session_revision = request.expected_session_revision
        idempotency_key = request.idempotency_key

    try:
        return ApplicationMessage(
            message_id=message_id,
            session_id=session_id,
            actor_id=actor_id,
            content=request.payload.get("content"),
            content_type=request.payload.get("content_type", _DEFAULT_CONTENT_TYPE),
            metadata=request.payload.get("metadata", {}),
            expected_session_revision=expected_session_revision,
            idempotency_key=idempotency_key,
        )
    except (TypeError, ValueError) as exc:
        # Malformed public text fails closed as an invalid request; it is never
        # reported as an internal defect.
        raise InvalidApplicationRequestError(
            details={"reason_code": "INVALID_MESSAGE"}
        ) from exc


class ApplicationGateway:
    """The one transport-neutral public entrypoint of the application backend."""

    def __init__(
        self,
        *,
        sessions: SessionApplicationService,
        requests: RequestApplicationService,
        capabilities: CapabilityApplicationService,
        health: HealthApplicationService,
        idempotency: InMemoryIdempotencyRepository,
    ) -> None:
        if not isinstance(sessions, SessionApplicationService):
            raise TypeError(
                "sessions must be the official SessionApplicationService, "
                f"not {type(sessions).__name__}"
            )
        if not isinstance(requests, RequestApplicationService):
            raise TypeError(
                "requests must be the official RequestApplicationService, "
                f"not {type(requests).__name__}"
            )
        if not isinstance(capabilities, CapabilityApplicationService):
            raise TypeError(
                "capabilities must be the official CapabilityApplicationService, "
                f"not {type(capabilities).__name__}"
            )
        if not isinstance(health, HealthApplicationService):
            raise TypeError(
                "health must be the official HealthApplicationService, "
                f"not {type(health).__name__}"
            )
        if not isinstance(idempotency, InMemoryIdempotencyRepository):
            raise TypeError(
                "idempotency must be the v1 InMemoryIdempotencyRepository, "
                f"not {type(idempotency).__name__}"
            )

        self._sessions = sessions
        self._requests = requests
        self._capabilities = capabilities
        self._health = health
        self._idempotency = idempotency
        # One private, in-process lock owns the keyed idempotency critical
        # section of *this* gateway instance.  It is an implementation detail:
        # it is not a constructor argument, not a service, not registered in
        # composition and not exported.  Commands without a key and queries
        # never touch it, and the v1 guarantee is deliberately local rather
        # than distributed.
        self._idempotency_lock = Lock()

    # ── Public entrypoint ────────────────────────────────────────────────────

    def handle(self, request: ApplicationRequest) -> ApplicationResponse:
        """Handle one public request, or fail closed with a safe response.

        A non-``ApplicationRequest`` is a caller defect at the direct Python
        boundary and raises ``TypeError``.  Every other defect of an accepted
        request becomes a safe failure response, so no exception text can cross
        the public boundary.
        """

        if not isinstance(request, ApplicationRequest):
            raise TypeError(
                f"request must be an ApplicationRequest, not {type(request).__name__}"
            )

        try:
            self._validate_role(request)
            return self._dispatch(request)
        except Exception as exc:  # noqa: BLE001 - the public boundary fails closed
            return failed_response(request.request_id, safe_error_from_exception(exc))

    # ── Validation ───────────────────────────────────────────────────────────

    @staticmethod
    def _validate_role(request: ApplicationRequest) -> None:
        """Fail closed unless the request role, operation and version agree."""

        operation = request.operation

        if isinstance(request, ApplicationCommand):
            mismatched = operation in QUERY_OPERATIONS
        elif isinstance(request, ApplicationQuery):
            mismatched = operation in COMMAND_OPERATIONS
        else:
            raise InvalidApplicationRequestError(
                details={"reason_code": "UNKNOWN_REQUEST_ROLE"}
            )

        if mismatched:
            raise InvalidApplicationRequestError(
                details={"reason_code": "OPERATION_KIND_MISMATCH"}
            )

        if request.api_version != APPLICATION_API_VERSION:
            raise UnsupportedApplicationVersionError()

    # ── Dispatch ─────────────────────────────────────────────────────────────

    def _dispatch(self, request: ApplicationRequest) -> ApplicationResponse:
        if request.operation in _IDEMPOTENT_OPERATIONS and isinstance(
            request, ApplicationCommand
        ):
            return self._dispatch_idempotent(request)
        return self._dispatch_once(request)

    def _dispatch_idempotent(self, request: ApplicationCommand) -> ApplicationResponse:
        """Replay, reject or record one keyed public command atomically.

        The whole keyed sequence — fingerprint, lookup, replay or conflict
        decision, canonical execution and record persistence — runs as one
        critical section, so a second caller of a key can never observe the
        absent record while the first is still executing the command.  The
        public replay/conflict semantics are unchanged; only the interleaving is
        closed.
        """

        key = request.idempotency_key
        if key is None:
            return self._dispatch_once(request)

        with self._idempotency_lock:
            fingerprint = fingerprint_command(request)
            stored = self._idempotency.get(key)
            if stored is not None:
                if stored.fingerprint != fingerprint:
                    raise IdempotencyConflictError(
                        details={"reason_code": "IDEMPOTENCY_KEY_REUSED"}
                    )
                return stored.response

            # Recording happens strictly after a terminal safe response exists.
            # A raised failure produced no response, so nothing is recorded for
            # it and the key is never bound to a defect.
            response = self._dispatch_once(request)
            self._idempotency.put(
                IdempotencyRecord(key=key, fingerprint=fingerprint, response=response)
            )
            return response

    def _dispatch_once(self, request: ApplicationRequest) -> ApplicationResponse:
        """Dispatch one of the six frozen public operations explicitly."""

        operation = request.operation

        if operation is ApplicationOperation.HEALTH_GET:
            return _success_response(
                request.request_id, self._health.get_health().to_dict()
            )

        if operation is ApplicationOperation.CAPABILITIES_LIST:
            return _success_response(
                request.request_id,
                {
                    "capabilities": [
                        capability.to_dict()
                        for capability in self._capabilities.list_capabilities()
                    ]
                },
            )

        if operation is ApplicationOperation.SESSION_CREATE:
            session = self._sessions.create_session(
                _session_id_from_payload(request.payload)
            )
            return _success_response(request.request_id, session.to_dict())

        if operation is ApplicationOperation.SESSION_GET:
            session_id = request.session_id
            if session_id is None:
                raise InvalidApplicationRequestError(
                    details={"reason_code": "MISSING_SESSION_ID"}
                )
            return _success_response(
                request.request_id, self._sessions.get_session(session_id).to_dict()
            )

        if operation is ApplicationOperation.MESSAGE_SUBMIT:
            return self._requests.submit_message(
                request_id=request.request_id,
                message=_message_from_request(request),
            )

        if operation is ApplicationOperation.REQUEST_CANCEL:
            return failed_response(
                request.request_id,
                ApplicationError(
                    code=ApplicationErrorCode.CAPABILITY_UNAVAILABLE,
                    message=CANCELLATION_UNAVAILABLE_MESSAGE,
                    retryable=False,
                    details={},
                ),
            )

        # Unreachable while the operation enum is closed and validated above; a
        # future operation therefore fails closed instead of being dispatched.
        raise InvalidApplicationRequestError(
            details={"reason_code": "UNKNOWN_OPERATION"}
        )
