services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      - TZ=Europe/Madrid
      - GENERIC_TIMEZONE=Europe/Madrid
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_RESTRICT_FILE_ACCESS_TO=/home/node/.n8n-files;/opt/cmm/config

    volumes:
      - ./n8n:/home/node/.n8n
      - ../config:/opt/cmm/config:ro
      - ../prompts:/opt/cmm/prompts:ro
