"""Phase 10.1 – Domain Intelligence Package.

Exports foundational contracts, enums, identifiers, and errors for the
Domain Intelligence subsystem.
"""

from __future__ import annotations

from cmm.cognitive.reasoning_rule_registry import InMemoryReasoningRuleRegistry

# Phase 10.8 – Domain Composition
from cmm.domains.composer import (
    DefaultDomainComposer,
    DomainComposer,
)
from cmm.domains.composition_contracts import (
    DomainComposition,
    DomainCompositionConflict,
    DomainCompositionDecision,
    DomainCompositionItem,
    DomainCompositionPolicy,
    EffectiveReasoningProfile,
    PermissionComposition,
    PresentationComposition,
)
from cmm.domains.contracts import (
    DomainCapability,
    DomainConflict,
    DomainDefinition,
    DomainDependency,
    DomainMetadata,
    DomainResult,
)

# Phase 10.9 – Cross-Domain Engine
from cmm.domains.cross_domain_aggregation import (
    DOMAIN_STATUS_PRECEDENCE,
    derive_confidence,
    derive_cross_domain_status,
    merge_contradictions,
    merge_dependencies,
    merge_domain_results,
    merge_findings,
    merge_gaps,
    merge_questions,
    merge_recommendations,
)
from cmm.domains.cross_domain_context import CrossDomainContextBuilder
from cmm.domains.cross_domain_contracts import (
    KNOWN_CROSS_DOMAIN_PORTS,
    CrossDomainContextSnapshot,
    CrossDomainContextTransfer,
    CrossDomainContradiction,
    CrossDomainDecision,
    CrossDomainDependency,
    CrossDomainDomainResult,
    CrossDomainFinding,
    CrossDomainGap,
    CrossDomainKnowledgeResult,
    CrossDomainLimits,
    CrossDomainOperationResult,
    CrossDomainPlanResult,
    CrossDomainPolicy,
    CrossDomainQuestion,
    CrossDomainRequest,
    CrossDomainResult,
    CrossDomainWorkflowResult,
)
from cmm.domains.cross_domain_engine import DefaultCrossDomainEngine
from cmm.domains.cross_domain_limits import CrossDomainLimitTracker
from cmm.domains.cross_domain_ports import (
    CrossDomainAgentPort,
    CrossDomainCognitivePort,
    CrossDomainEngine,
    CrossDomainKnowledgePort,
    CrossDomainOperationPort,
    CrossDomainPlannerPort,
    CrossDomainWorkflowPort,
    DomainCompositionPort,
    DomainResolutionPort,
)
from cmm.domains.discovery import (
    DomainDiscovery,
    FileSystemDomainDiscovery,
)
from cmm.domains.discovery_contracts import (
    DomainCandidate,
    DomainDiscoveryIssue,
    DomainDiscoveryResult,
    DomainSource,
)
from cmm.domains.enums import (
    CrossDomainSeverity,
    CrossDomainStage,
    CrossDomainStatus,
    DomainCompositionStatus,
    DomainConflictPolicy,
    DomainKind,
    DomainLoadStatus,
    DomainOperationStatus,
    DomainOperationType,
    DomainPackKind,
    DomainPackStatus,
    DomainProfileConflictSeverity,
    DomainProfileDecisionCode,
    DomainProfileResolutionStatus,
    DomainProfileSource,
    DomainReasoningDepth,
    DomainResolutionStatus,
    DomainResourceDecisionCode,
    DomainResourceResolutionStatus,
    DomainResourceValidationOperator,
    DomainResourceValidationSeverity,
    DomainRuleConflictSeverity,
    DomainRuleExecutionStatus,
    DomainRuleSelectionDecisionCode,
    DomainRuleSelectionStatus,
    DomainRuleSource,
    DomainSourceKind,
    DomainStatus,
    DomainValidationStatus,
)
from cmm.domains.errors import (
    CrossDomainConfigurationError,
    CrossDomainContractError,
    CrossDomainError,
    CrossDomainExecutionError,
    CrossDomainLimitError,
    CrossDomainPortError,
    CrossDomainSerializationError,
    DomainCandidateInvalid,
    DomainCapabilityConflict,
    DomainChecksumMismatch,
    DomainCompositionConfigurationError,
    DomainCompositionContractError,
    DomainCompositionError,
    DomainCompositionExecutionError,
    DomainCompositionSerializationError,
    DomainContractError,
    DomainContractValidationError,
    DomainDependencyMissing,
    DomainDiscoveryError,
    DomainDiscoverySourceError,
    DomainError,
    DomainLoaderError,
    DomainLoadFailed,
    DomainLoadRejected,
    DomainLoadRollbackFailed,
    DomainOperationApprovalRequiredError,
    DomainOperationCancellationError,
    DomainOperationContractError,
    DomainOperationError,
    DomainOperationExecutionError,
    DomainOperationPermissionDeniedError,
    DomainOperationRegistryError,
    DomainOperationResolutionError,
    DomainOperationRollbackError,
    DomainOperationSerializationError,
    DomainOperationUnavailableError,
    DomainOperationValidationError,
    DomainPathEscape,
    DomainPermissionApprovalRequiredError,
    DomainPermissionConflictError,
    DomainPermissionContractError,
    DomainPermissionCrossDomainError,
    DomainPermissionDeniedError,
    DomainPermissionError,
    DomainPermissionEvaluationError,
    DomainPermissionRegistryError,
    DomainPermissionResolutionError,
    DomainPermissionSerializationError,
    DomainProfileCompositionError,
    DomainProfileConfigurationError,
    DomainProfileContractError,
    DomainProfileError,
    DomainProfileRegistryError,
    DomainProfileResolutionError,
    DomainProfileSerializationError,
    DomainRegistryConflict,
    DomainRegistryError,
    DomainRegistryNotFound,
    DomainRegistryStateError,
    DomainRegistryValidationError,
    DomainRegistryVersionError,
    DomainReloadFailed,
    DomainReloadRollbackFailed,
    DomainResolutionAmbiguityError,
    DomainResolutionBlockedError,
    DomainResolutionContextInvalid,
    DomainResolutionContractError,
    DomainResolutionError,
    DomainResolutionLimitExceeded,
    DomainResolutionPolicyError,
    DomainResolutionSerializationError,
    DomainResolutionSnapshotError,
    DomainResolutionUnsupportedError,
    DomainResolverConfigurationError,
    DomainResolverError,
    DomainResolverExecutionError,
    DomainResourceConfigurationError,
    DomainResourceContractError,
    DomainResourceDerivationError,
    DomainResourceError,
    DomainResourceRegistryError,
    DomainResourceResolutionError,
    DomainResourceSerializationError,
    DomainRollbackFailed,
    DomainRuleConfigurationError,
    DomainRuleContractError,
    DomainRuleError,
    DomainRuleExecutionError,
    DomainRuleSelectionError,
    DomainRuleSerializationError,
    DomainSerializationError,
    DomainSourceUntrusted,
    DomainUnloadFailed,
    DomainUnloadRollbackFailed,
    DomainValidationBlocked,
    DomainValidationContextInvalid,
    DomainValidationError,
    DomainValidationExecutionError,
    DomainValidationRequestInvalid,
    DomainValidationStepMissing,
)
from cmm.domains.identifiers import (
    DomainId,
    DomainManifestId,
    DomainResultId,
)
from cmm.domains.loader import (
    DeclarativeDomainLoader,
    DomainLoader,
)
from cmm.domains.loader_contracts import (
    DomainLoaderSnapshot,
    DomainLoadResult,
)
from cmm.domains.manifest import (
    DomainCompatibility,
    DomainComponentReference,
    DomainManifest,
    DomainPermissionReference,
)
from cmm.domains.manifest_reader import (
    DomainManifestDocument,
    DomainManifestReader,
    JsonDomainManifestReader,
)
from cmm.domains.operation_approval import build_domain_operation_approval_requirement
from cmm.domains.operation_availability import (
    DomainOperationAvailability,
    DomainOperationAvailabilityContext,
    DomainOperationAvailabilityResolver,
)
from cmm.domains.operation_catalog import (
    INITIAL_DOMAIN_OPERATION_IDS,
    build_initial_domain_operation_catalog,
)
from cmm.domains.operation_contracts import (
    DomainOperationContext,
    DomainOperationDefinition,
    DomainOperationRequest,
    DomainOperationResult,
    DomainOperationRollbackResult,
    DomainOperationTraceEntry,
    validate_domain_operation_transition,
)
from cmm.domains.operation_execution import (
    DefaultDomainOperationOrchestrator,
    DomainOperationExecutionDelegate,
)
from cmm.domains.operation_registry import InMemoryDomainOperationRegistry
from cmm.domains.pack import (
    DomainPack,
    ParsedDomainPack,
)

# Phase 10.11 – Domain Profiles
from cmm.domains.profile_composition import (
    DefaultDomainProfileComposer,
    DomainProfileComposer,
)
from cmm.domains.profile_contracts import (
    DomainMemoryPolicy,
    DomainPresentationPolicy,
    DomainProductionPolicy,
    DomainProfileCompositionResult,
    DomainProfileConflict,
    DomainProfileDecision,
    DomainProfileDefinition,
    DomainProfileDraft,
    DomainProfileModification,
    DomainProfileOverlay,
    DomainProfileRejection,
    DomainProfileResolution,
    DomainProfileResolutionRequest,
    DomainQuestionPolicy,
    DomainTemporalPolicy,
    ResolvedDomainProfile,
)
from cmm.domains.profile_registry import (
    INITIAL_DOMAIN_PROFILE_NAMES,
    DomainProfileRegistry,
    InMemoryDomainProfileRegistry,
)
from cmm.domains.profile_resolver import (
    DefaultDomainProfileResolver,
    DomainProfileResolver,
)
from cmm.domains.registry import (
    DomainRegistry,
)
from cmm.domains.registry_contracts import (
    DomainQuery,
    DomainRegistryRecord,
    DomainRegistrySnapshot,
    DomainRegistryStoreSnapshot,
    DomainValidationResult,
)
from cmm.domains.registry_store import (
    DomainRegistryStore,
    InMemoryDomainRegistryStore,
)
from cmm.domains.registry_validation import (
    DomainDefinitionRegistryValidator,
)

# Phase 10.6 – Domain Resolution Context
from cmm.domains.resolution_builder import (
    DomainResolutionContextBuilder,
)
from cmm.domains.resolution_contracts import (
    DomainResolutionContext,
    DomainResolutionEntity,
    DomainResolutionEvent,
    DomainResolutionHistoryItem,
    DomainResolutionKnowledgeItem,
    DomainResolutionPolicy,
    DomainResolutionResource,
    DomainResolutionSignal,
)

# Phase 10.7 – Domain Resolver
from cmm.domains.resolver import (
    DefaultDomainResolver,
    DomainResolver,
)
from cmm.domains.resolver_contracts import (
    DomainCandidateScore,
    DomainResolutionReason,
    DomainResolutionResult,
    DomainScoringPolicy,
)
from cmm.domains.resolver_scoring import (
    DomainCandidateScorer,
)

# Phase 10.10 – Domain Resources
from cmm.domains.resource_contracts import (
    DomainResourceBinding,
    DomainResourceChecksum,
    DomainResourceContext,
    DomainResourceDecision,
    DomainResourceDefinition,
    DomainResourceDerivation,
    DomainResourceRejection,
    DomainResourceResolution,
    DomainResourceTemporalPolicy,
    DomainResourceValidationResult,
    DomainResourceValidationRule,
)
from cmm.domains.resource_derivation import DomainResourceDerivationService
from cmm.domains.resource_registry import (
    DomainResourceRegistry,
    InMemoryDomainResourceRegistry,
)
from cmm.domains.resource_resolver import (
    DefaultDomainResourceResolver,
    DefaultDomainResourceValidator,
    DomainResourceResolver,
    DomainResourceValidator,
)

# Phase 10.12 – Domain Rules
from cmm.domains.rule_catalog import (
    INITIAL_DOMAIN_REASONING_RULE_IDS,
    build_initial_reasoning_rule_catalog,
)
from cmm.domains.rule_contracts import (
    DOMAIN_RULE_CONTRACT_VERSION,
    DomainReasoningRuleDefinition,
    DomainRuleExecutionPlan,
    DomainRuleExecutionPolicy,
    DomainRuleExecutionResult,
    DomainRuleResult,
    DomainRuleSelectionConflict,
    DomainRuleSelectionDecision,
    DomainRuleSelectionPolicy,
    DomainRuleSourceRecord,
    SelectedReasoningRule,
)
from cmm.domains.rule_execution import (
    DefaultDomainRuleExecutor,
    DomainRuleExecutor,
)
from cmm.domains.rule_selection import (
    DefaultDomainRuleSelector,
    DomainRuleSelector,
)

# Phase 10.5 – Domain Validation
from cmm.domains.validation import (
    PipelineDomainValidator,
    build_domain_validation_result,
    ensure_domain_validation_allows_install,
)
from cmm.domains.validation_context import (
    build_domain_validation_context,
)
from cmm.domains.validation_contracts import (
    DomainValidationExecutionContext,
    DomainValidationRequest,
)
from cmm.domains.validation_contracts import (
    DomainValidationResult as DomainValidationResult10,
)
from cmm.domains.validation_steps import (
    ALL_DOMAIN_STEPS,
    build_domain_validation_steps,
)

__all__ = [
    "ALL_DOMAIN_STEPS",
    "DOMAIN_RULE_CONTRACT_VERSION",
    "DOMAIN_STATUS_PRECEDENCE",
    "INITIAL_DOMAIN_OPERATION_IDS",
    "INITIAL_DOMAIN_PROFILE_NAMES",
    "INITIAL_DOMAIN_REASONING_RULE_IDS",
    "KNOWN_CROSS_DOMAIN_PORTS",
    "CrossDomainAgentPort",
    "CrossDomainCognitivePort",
    "CrossDomainConfigurationError",
    "CrossDomainContextBuilder",
    "CrossDomainContextSnapshot",
    "CrossDomainContextTransfer",
    "CrossDomainContractError",
    "CrossDomainContradiction",
    "CrossDomainDecision",
    "CrossDomainDependency",
    "CrossDomainDomainResult",
    "CrossDomainEngine",
    "CrossDomainError",
    "CrossDomainExecutionError",
    "CrossDomainFinding",
    "CrossDomainGap",
    "CrossDomainKnowledgePort",
    "CrossDomainKnowledgeResult",
    "CrossDomainLimitError",
    "CrossDomainLimitTracker",
    "CrossDomainLimits",
    "CrossDomainOperationPort",
    "CrossDomainOperationResult",
    "CrossDomainPlanResult",
    "CrossDomainPlannerPort",
    "CrossDomainPolicy",
    "CrossDomainPortError",
    "CrossDomainQuestion",
    "CrossDomainRequest",
    "CrossDomainResult",
    "CrossDomainSerializationError",
    "CrossDomainSeverity",
    "CrossDomainStage",
    "CrossDomainStatus",
    "CrossDomainWorkflowPort",
    "CrossDomainWorkflowResult",
    "DeclarativeDomainLoader",
    "DefaultCrossDomainEngine",
    "DefaultDomainComposer",
    "DefaultDomainOperationOrchestrator",
    "DefaultDomainProfileComposer",
    "DefaultDomainProfileResolver",
    "DefaultDomainResolver",
    "DefaultDomainResourceResolver",
    "DefaultDomainResourceValidator",
    "DefaultDomainRuleExecutor",
    "DefaultDomainRuleSelector",
    "DomainCandidate",
    "DomainCandidateInvalid",
    "DomainCandidateScore",
    "DomainCandidateScorer",
    "DomainCapability",
    "DomainCapabilityConflict",
    "DomainChecksumMismatch",
    "DomainCompatibility",
    "DomainComponentReference",
    "DomainComposer",
    "DomainComposition",
    "DomainCompositionConfigurationError",
    "DomainCompositionConflict",
    "DomainCompositionContractError",
    "DomainCompositionDecision",
    "DomainCompositionError",
    "DomainCompositionExecutionError",
    "DomainCompositionItem",
    "DomainCompositionPolicy",
    "DomainCompositionPort",
    "DomainCompositionSerializationError",
    "DomainCompositionStatus",
    "DomainConflict",
    "DomainConflictPolicy",
    "DomainContractError",
    "DomainContractValidationError",
    "DomainDefinition",
    "DomainDefinitionRegistryValidator",
    "DomainDependency",
    "DomainDependencyMissing",
    "DomainDiscovery",
    "DomainDiscoveryError",
    "DomainDiscoveryIssue",
    "DomainDiscoveryResult",
    "DomainDiscoverySourceError",
    "DomainError",
    "DomainId",
    "DomainKind",
    "DomainLoadFailed",
    "DomainLoadRejected",
    "DomainLoadResult",
    "DomainLoadRollbackFailed",
    "DomainLoadStatus",
    "DomainLoader",
    "DomainLoaderError",
    "DomainLoaderSnapshot",
    "DomainManifest",
    "DomainManifestDocument",
    "DomainManifestId",
    "DomainManifestReader",
    "DomainMemoryPolicy",
    "DomainMetadata",
    "DomainOperationApprovalRequiredError",
    "DomainOperationAvailability",
    "DomainOperationAvailabilityContext",
    "DomainOperationAvailabilityResolver",
    "DomainOperationCancellationError",
    "DomainOperationContext",
    "DomainOperationContractError",
    "DomainOperationDefinition",
    "DomainOperationError",
    "DomainOperationExecutionDelegate",
    "DomainOperationExecutionError",
    "DomainOperationPermissionDeniedError",
    "DomainOperationRegistryError",
    "DomainOperationRequest",
    "DomainOperationResolutionError",
    "DomainOperationResult",
    "DomainOperationRollbackError",
    "DomainOperationRollbackResult",
    "DomainOperationSerializationError",
    "DomainOperationStatus",
    "DomainOperationTraceEntry",
    "DomainOperationType",
    "DomainOperationUnavailableError",
    "DomainOperationValidationError",
    "DomainPack",
    "DomainPackKind",
    "DomainPackStatus",
    "DomainPathEscape",
    "DomainPermissionReference",
    "DomainPresentationPolicy",
    "DomainProductionPolicy",
    "DomainProfileComposer",
    "DomainProfileCompositionError",
    "DomainProfileCompositionResult",
    "DomainProfileConfigurationError",
    "DomainProfileConflict",
    "DomainProfileConflictSeverity",
    "DomainProfileContractError",
    "DomainProfileDecision",
    "DomainProfileDecisionCode",
    "DomainProfileDefinition",
    "DomainProfileDraft",
    "DomainProfileError",
    "DomainProfileModification",
    "DomainProfileOverlay",
    "DomainProfileRegistry",
    "DomainProfileRegistryError",
    "DomainProfileRejection",
    "DomainProfileResolution",
    "DomainProfileResolutionError",
    "DomainProfileResolutionRequest",
    "DomainProfileResolutionStatus",
    "DomainProfileResolver",
    "DomainProfileSerializationError",
    "DomainProfileSource",
    "DomainQuery",
    "DomainQuestionPolicy",
    "DomainReasoningDepth",
    "DomainReasoningRuleDefinition",
    "DomainRegistry",
    "DomainRegistryConflict",
    "DomainRegistryError",
    "DomainRegistryNotFound",
    "DomainRegistryRecord",
    "DomainRegistrySnapshot",
    "DomainRegistryStateError",
    "DomainRegistryStore",
    "DomainRegistryStoreSnapshot",
    "DomainRegistryValidationError",
    "DomainRegistryVersionError",
    "DomainReloadFailed",
    "DomainReloadRollbackFailed",
    "DomainResolutionAmbiguityError",
    "DomainResolutionBlockedError",
    "DomainResolutionContext",
    "DomainResolutionContextBuilder",
    "DomainResolutionContextInvalid",
    "DomainResolutionContractError",
    "DomainResolutionEntity",
    "DomainResolutionError",
    "DomainResolutionEvent",
    "DomainResolutionHistoryItem",
    "DomainResolutionKnowledgeItem",
    "DomainResolutionLimitExceeded",
    "DomainResolutionPolicy",
    "DomainResolutionPolicyError",
    "DomainResolutionPort",
    "DomainResolutionReason",
    "DomainResolutionResource",
    "DomainResolutionResult",
    "DomainResolutionSerializationError",
    "DomainResolutionSignal",
    "DomainResolutionSnapshotError",
    "DomainResolutionStatus",
    "DomainResolutionUnsupportedError",
    "DomainResolver",
    "DomainResolverConfigurationError",
    "DomainResolverError",
    "DomainResolverExecutionError",
    "DomainResourceBinding",
    "DomainResourceChecksum",
    "DomainResourceConfigurationError",
    "DomainResourceContext",
    "DomainResourceContractError",
    "DomainResourceDecision",
    "DomainResourceDecisionCode",
    "DomainResourceDefinition",
    "DomainResourceDerivation",
    "DomainResourceDerivationError",
    "DomainResourceDerivationService",
    "DomainResourceError",
    "DomainResourceRegistry",
    "DomainResourceRegistryError",
    "DomainResourceRejection",
    "DomainResourceResolution",
    "DomainResourceResolutionError",
    "DomainResourceResolutionStatus",
    "DomainResourceResolver",
    "DomainResourceSerializationError",
    "DomainResourceTemporalPolicy",
    "DomainResourceValidationOperator",
    "DomainResourceValidationResult",
    "DomainResourceValidationRule",
    "DomainResourceValidationSeverity",
    "DomainResourceValidator",
    "DomainResult",
    "DomainResultId",
    "DomainRollbackFailed",
    "DomainRuleConfigurationError",
    "DomainRuleConflictSeverity",
    "DomainRuleContractError",
    "DomainRuleError",
    "DomainRuleExecutionError",
    "DomainRuleExecutionPlan",
    "DomainRuleExecutionPolicy",
    "DomainRuleExecutionResult",
    "DomainRuleExecutionStatus",
    "DomainRuleExecutor",
    "DomainRuleResult",
    "DomainRuleSelectionConflict",
    "DomainRuleSelectionDecision",
    "DomainRuleSelectionDecisionCode",
    "DomainRuleSelectionError",
    "DomainRuleSelectionPolicy",
    "DomainRuleSelectionStatus",
    "DomainRuleSelector",
    "DomainRuleSerializationError",
    "DomainRuleSource",
    "DomainRuleSourceRecord",
    "DomainScoringPolicy",
    "DomainSerializationError",
    "DomainSource",
    "DomainSourceKind",
    "DomainSourceUntrusted",
    "DomainStatus",
    "DomainTemporalPolicy",
    "DomainUnloadFailed",
    "DomainUnloadRollbackFailed",
    "DomainValidationBlocked",
    "DomainValidationContextInvalid",
    "DomainValidationError",
    "DomainValidationExecutionContext",
    "DomainValidationExecutionError",
    "DomainValidationRequest",
    "DomainValidationRequestInvalid",
    "DomainValidationResult",
    "DomainValidationResult10",
    "DomainValidationStatus",
    "DomainValidationStepMissing",
    "EffectiveReasoningProfile",
    "FileSystemDomainDiscovery",
    "InMemoryDomainOperationRegistry",
    "InMemoryDomainProfileRegistry",
    "InMemoryDomainRegistryStore",
    "InMemoryDomainResourceRegistry",
    "InMemoryReasoningRuleRegistry",
    "JsonDomainManifestReader",
    "ParsedDomainPack",
    "PermissionComposition",
    "PipelineDomainValidator",
    "PresentationComposition",
    "ResolvedDomainProfile",
    "SelectedReasoningRule",
    "build_domain_operation_approval_requirement",
    "build_domain_validation_context",
    "build_domain_validation_result",
    "build_domain_validation_steps",
    "build_initial_domain_operation_catalog",
    "build_initial_reasoning_rule_catalog",
    "derive_confidence",
    "derive_cross_domain_status",
    "ensure_domain_validation_allows_install",
    "merge_contradictions",
    "merge_dependencies",
    "merge_domain_results",
    "merge_findings",
    "merge_gaps",
    "merge_questions",
    "merge_recommendations",
    "validate_domain_operation_transition",
]

from cmm.domains.errors import (
    DomainPresentationConflictError,
    DomainPresentationContractError,
    DomainPresentationError,
    DomainPresentationOutputIntentError,
    DomainPresentationPolicyError,
    DomainPresentationPreservationError,
    DomainPresentationRequiredSectionError,
    DomainPresentationSerializationError,
    DomainPresentationTerminologyError,
    DomainPresentationUnknownReferenceError,
    DomainPresentationWarningPriorityError,
    DomainTraceContractError,
    DomainTraceError,
    DomainTraceSerializationError,
    DomainTraceValidationError,
)
from cmm.domains.permission_adapters import (
    DomainOperationPermissionDecision,
    DomainRulePermissionDecision,
    DomainWorkflowPermissionDecision,
    evaluate_domain_operation,
    evaluate_domain_rule,
    evaluate_domain_workflow,
    evaluate_domain_workflow_node,
    request_for_operation,
    request_for_rule_permission,
    request_for_workflow,
)
from cmm.domains.permission_catalog import build_initial_permission_catalog
from cmm.domains.permission_contracts import (
    CrossDomainDuration,
    CrossDomainPermissionDecision,
    CrossDomainPermissionRequest,
    DomainAutonomyLimits,
    DomainPermissionConflict,
    DomainPermissionPolicy,
    DomainPermissionRequest,
)
from cmm.domains.permission_evaluator import evaluate_domain_policy
from cmm.domains.permission_gate import (
    DomainPermissionGate,
    PermissionGateOutcome,
    PermissionGateReason,
    PermissionGateResult,
)
from cmm.domains.permission_registry import DomainPermissionRegistry
from cmm.domains.permission_resolution import (
    DomainPermissionResolution,
    DomainPermissionResolver,
)
from cmm.domains.presentation_contracts import (
    DomainOutputIntent,
    DomainOutputIntentType,
    DomainPresentationComponentDescriptor,
    DomainPresentationConflict,
    DomainPresentationConflictCode,
    DomainPresentationDecision,
    DomainPresentationDecisionCode,
    DomainPresentationEpistemicKind,
    DomainPresentationItemRef,
    DomainPresentationItemType,
    DomainPresentationPlan,
    DomainPresentationRequest,
    DomainPresentationSectionPlan,
    DomainPresentationValidationCode,
    DomainPresentationValidationResult,
    DomainPresentationValidationState,
)
from cmm.domains.trace_assembler import DomainTraceAssembler
from cmm.domains.trace_contracts import (
    CrossDomainTraceReference,
    DomainResultTraceReference,
    DomainTrace,
    DomainTraceAssemblyRequest,
    DomainTraceContribution,
    DomainTraceDomainSelection,
    DomainTraceReference,
    DomainTraceReferenceInventory,
    DomainTraceReferenceKind,
    DomainTraceReferences,
    DomainTraceRole,
    DomainTraceStatus,
    DomainTraceValidationCode,
    DomainTraceValidationResult,
    DomainTraceValidationState,
)
from cmm.domains.trace_validation import (
    DefaultDomainTraceReferenceValidator,
    DomainTraceReferenceValidator,
)
from cmm.domains.presentation_planner import (
    DefaultDomainPresentationPlanner,
    DomainPresentationPlanner,
)
from cmm.domains.presentation_validation import (
    DefaultDomainPresentationPreservationValidator,
    DomainPresentationPreservationValidator,
)

__all__ += [
    "CrossDomainDuration",
    "CrossDomainPermissionDecision",
    "CrossDomainPermissionRequest",
    "DefaultDomainPresentationPlanner",
    "DefaultDomainPresentationPreservationValidator",
    "DomainAutonomyLimits",
    "DomainOperationPermissionDecision",
    "DomainOutputIntent",
    "DomainOutputIntentType",
    "DomainPermissionApprovalRequiredError",
    "DomainPermissionConflict",
    "DomainPermissionConflictError",
    "DomainPermissionContractError",
    "DomainPermissionCrossDomainError",
    "DomainPermissionDeniedError",
    "DomainPermissionError",
    "DomainPermissionEvaluationError",
    "DomainPermissionGate",
    "DomainPermissionPolicy",
    "DomainPermissionRegistry",
    "DomainPermissionRegistryError",
    "DomainPermissionRequest",
    "DomainPermissionResolution",
    "DomainPermissionResolutionError",
    "DomainPermissionResolver",
    "DomainPermissionSerializationError",
    "DomainPresentationComponentDescriptor",
    "DomainPresentationConflict",
    "DomainPresentationConflictCode",
    "DomainPresentationConflictError",
    "DomainPresentationContractError",
    "DomainPresentationDecision",
    "DomainPresentationDecisionCode",
    "DomainPresentationEpistemicKind",
    "DomainPresentationError",
    "DomainPresentationItemRef",
    "DomainPresentationItemType",
    "DomainPresentationOutputIntentError",
    "DomainPresentationPlan",
    "DomainPresentationPlanner",
    "DomainPresentationPolicyError",
    "DomainPresentationPreservationError",
    "DomainPresentationPreservationValidator",
    "DomainPresentationRequest",
    "DomainPresentationRequiredSectionError",
    "DomainPresentationSectionPlan",
    "DomainPresentationSerializationError",
    "DomainPresentationTerminologyError",
    "DomainPresentationUnknownReferenceError",
    "DomainPresentationValidationCode",
    "DomainPresentationValidationResult",
    "DomainPresentationValidationState",
    "DomainPresentationWarningPriorityError",
    "DefaultDomainTraceReferenceValidator",
    "CrossDomainTraceReference",
    "DomainResultTraceReference",
    "DomainTrace",
    "DomainTraceAssembler",
    "DomainTraceAssemblyRequest",
    "DomainTraceContribution",
    "DomainTraceDomainSelection",
    "DomainTraceContractError",
    "DomainTraceError",
    "DomainTraceReferenceValidator",
    "DomainTraceReference",
    "DomainTraceReferenceInventory",
    "DomainTraceReferenceKind",
    "DomainTraceReferences",
    "DomainTraceRole",
    "DomainTraceSerializationError",
    "DomainTraceStatus",
    "DomainTraceValidationCode",
    "DomainTraceValidationError",
    "DomainTraceValidationResult",
    "DomainTraceValidationState",
    "DomainRulePermissionDecision",
    "DomainWorkflowPermissionDecision",
    "PermissionGateOutcome",
    "PermissionGateReason",
    "PermissionGateResult",
    "build_initial_permission_catalog",
    "evaluate_domain_operation",
    "evaluate_domain_policy",
    "evaluate_domain_rule",
    "evaluate_domain_workflow",
    "evaluate_domain_workflow_node",
    "request_for_operation",
    "request_for_rule_permission",
    "request_for_workflow",
]
