"""Phase 10.27 — Parenthood Domain package.

A pedagogical, proposal-only, fail-closed Domain Pack for parenthood journey planning,
pathway comparison, child developmental tracking, routine management, and educational guidance.

Public package surface only; no import-time registration or side effects.
"""

from __future__ import annotations

from cmm.domains.parenthood.bootstrap import (
    PARENTHOOD_BOOTSTRAP_NAME,
    ParenthoodDomainBootstrap,
    build_standard_parenthood_domain_bootstrap,
)
from cmm.domains.parenthood.catalog import (
    CANONICAL_PARENTHOOD_CHILD_ENTITY_TYPES,
    CANONICAL_PARENTHOOD_CHILD_OPERATION_IDS,
    CANONICAL_PARENTHOOD_CHILD_RULE_IDS,
    CANONICAL_PARENTHOOD_CHILD_WORKFLOW_IDS,
    CANONICAL_PARENTHOOD_ENTITY_TYPES,
    CANONICAL_PARENTHOOD_JOURNEY_ENTITY_TYPES,
    CANONICAL_PARENTHOOD_JOURNEY_OPERATION_IDS,
    CANONICAL_PARENTHOOD_JOURNEY_RULE_IDS,
    CANONICAL_PARENTHOOD_JOURNEY_WORKFLOW_IDS,
    CANONICAL_PARENTHOOD_OPERATION_IDS,
    CANONICAL_PARENTHOOD_RESOURCE_IDS,
    CANONICAL_PARENTHOOD_RULE_IDS,
    CANONICAL_PARENTHOOD_RULE_NAMES,
    CANONICAL_PARENTHOOD_WORKFLOW_IDS,
    CANONICAL_PARENTHOOD_WORKFLOW_NAMES,
    PARENTHOOD_RESOURCE_KINDS,
    PARENTHOOD_WORKFLOW_NAMES_BY_ID,
)
from cmm.domains.parenthood.definition import (
    PARENTHOOD_DOMAIN_ID,
    PARENTHOOD_DOMAIN_VERSION,
    PARENTHOOD_MANIFEST_ID,
    PARENTHOOD_OPERATION_IDS,
    PARENTHOOD_PERMISSION_IDS,
    PARENTHOOD_PROFILE_NAME,
    PARENTHOOD_RESOURCE_IDS,
    PARENTHOOD_RULE_IDS,
    PARENTHOOD_WORKFLOW_IDS,
    build_parenthood_domain_definition,
)
from cmm.domains.parenthood.integration import (
    ParenthoodDomainIntegrationResult,
    register_parenthood_domain,
)
from cmm.domains.parenthood.memory import (
    CANDIDATE_LONGITUDINAL_KINDS,
    build_parenthood_memory_binding,
    build_parenthood_memory_proposal,
    build_parenthood_memory_view,
    build_parenthood_memory_view_request,
    validate_parenthood_memory_binding,
)
from cmm.domains.parenthood.operations import (
    build_parenthood_operation_definitions,
    build_timeline_result,
    compare_pathways_result,
    plan_routines_result,
    prepare_parental_decision_result,
    review_developmental_stage_result,
)
from cmm.domains.parenthood.permissions import (
    PARENTHOOD_PERMISSION_POLICY_ID,
    PARENTHOOD_PROHIBITED_CAPABILITIES,
    build_parenthood_permission_policy,
    permission_authorization_allows,
    persistence_confirmation_accepted,
)
from cmm.domains.parenthood.presentation import (
    build_parenthood_presentation_policy,
    present_parenthood_result,
)
from cmm.domains.parenthood.profile import (
    PARENTHOOD_PROFILE_ID,
    PARENTHOOD_PROHIBITED_ACTIONS,
    build_parenthood_profile,
)
from cmm.domains.parenthood.resources import (
    build_parenthood_resource_definitions,
)
from cmm.domains.parenthood.rules import (
    AgeAppropriateGuidanceRule,
    ChildInterestAndWellbeingRule,
    CostUncertaintyRule,
    DevelopmentalContextRule,
    EducationBoundaryRule,
    EthicalConstraintRule,
    HealthBoundaryRule,
    JourneyDependencyRule,
    JourneyToChildBoundaryRule,
    LegalTemporalValidityRule,
    LongTermContinuityRule,
    MedicalLegalSeparationRule,
    MinorPrivacyRule,
    ParentChildBoundaryRule,
    ParentalUncertaintyRule,
    ParenthoodDecisionExplicitRule,
    SiblingIdentityIsolationRule,
    build_parenthood_rules,
)
from cmm.domains.parenthood.trace import (
    assemble_parenthood_trace,
    build_parenthood_trace_contribution,
    build_parenthood_trace_reference,
    build_supporting_trace_contribution,
    validate_parenthood_trace,
)
from cmm.domains.parenthood.workflows import (
    build_parenthood_workflow_definitions,
)
from cmm.domains.parenthood.workspaces import (
    ChildParentingWorkspace,
    ParenthoodScope,
    build_child_workspace,
    ensure_sibling_identity_isolation,
    parse_parenthood_scope,
    select_journey_transfer_candidates,
    validate_child_workspace,
)

__all__ = [
    "AgeAppropriateGuidanceRule",
    "CANDIDATE_LONGITUDINAL_KINDS",
    "CANONICAL_PARENTHOOD_CHILD_ENTITY_TYPES",
    "CANONICAL_PARENTHOOD_CHILD_OPERATION_IDS",
    "CANONICAL_PARENTHOOD_CHILD_RULE_IDS",
    "CANONICAL_PARENTHOOD_CHILD_WORKFLOW_IDS",
    "CANONICAL_PARENTHOOD_ENTITY_TYPES",
    "CANONICAL_PARENTHOOD_JOURNEY_ENTITY_TYPES",
    "CANONICAL_PARENTHOOD_JOURNEY_OPERATION_IDS",
    "CANONICAL_PARENTHOOD_JOURNEY_RULE_IDS",
    "CANONICAL_PARENTHOOD_JOURNEY_WORKFLOW_IDS",
    "CANONICAL_PARENTHOOD_OPERATION_IDS",
    "CANONICAL_PARENTHOOD_RESOURCE_IDS",
    "CANONICAL_PARENTHOOD_RULE_IDS",
    "CANONICAL_PARENTHOOD_RULE_NAMES",
    "CANONICAL_PARENTHOOD_WORKFLOW_IDS",
    "CANONICAL_PARENTHOOD_WORKFLOW_NAMES",
    "ChildInterestAndWellbeingRule",
    "ChildParentingWorkspace",
    "CostUncertaintyRule",
    "DevelopmentalContextRule",
    "EducationBoundaryRule",
    "EthicalConstraintRule",
    "HealthBoundaryRule",
    "JourneyDependencyRule",
    "JourneyToChildBoundaryRule",
    "LegalTemporalValidityRule",
    "LongTermContinuityRule",
    "MedicalLegalSeparationRule",
    "MinorPrivacyRule",
    "PARENTHOOD_BOOTSTRAP_NAME",
    "PARENTHOOD_DOMAIN_ID",
    "PARENTHOOD_DOMAIN_VERSION",
    "PARENTHOOD_MANIFEST_ID",
    "PARENTHOOD_OPERATION_IDS",
    "PARENTHOOD_PERMISSION_IDS",
    "PARENTHOOD_PERMISSION_POLICY_ID",
    "PARENTHOOD_PROFILE_ID",
    "PARENTHOOD_PROFILE_NAME",
    "PARENTHOOD_PROHIBITED_ACTIONS",
    "PARENTHOOD_PROHIBITED_CAPABILITIES",
    "PARENTHOOD_RESOURCE_IDS",
    "PARENTHOOD_RESOURCE_KINDS",
    "PARENTHOOD_RULE_IDS",
    "PARENTHOOD_WORKFLOW_IDS",
    "PARENTHOOD_WORKFLOW_NAMES_BY_ID",
    "ParentChildBoundaryRule",
    "ParentalUncertaintyRule",
    "ParenthoodDecisionExplicitRule",
    "ParenthoodDomainBootstrap",
    "ParenthoodDomainIntegrationResult",
    "ParenthoodScope",
    "SiblingIdentityIsolationRule",
    "assemble_parenthood_trace",
    "build_child_workspace",
    "build_parenthood_domain_definition",
    "build_parenthood_memory_binding",
    "build_parenthood_memory_proposal",
    "build_parenthood_memory_view",
    "build_parenthood_memory_view_request",
    "build_parenthood_operation_definitions",
    "build_parenthood_permission_policy",
    "build_parenthood_presentation_policy",
    "build_parenthood_profile",
    "build_parenthood_resource_definitions",
    "build_parenthood_rules",
    "build_parenthood_trace_contribution",
    "build_parenthood_trace_reference",
    "build_parenthood_workflow_definitions",
    "build_standard_parenthood_domain_bootstrap",
    "build_supporting_trace_contribution",
    "build_timeline_result",
    "compare_pathways_result",
    "ensure_sibling_identity_isolation",
    "parse_parenthood_scope",
    "permission_authorization_allows",
    "persistence_confirmation_accepted",
    "plan_routines_result",
    "prepare_parental_decision_result",
    "present_parenthood_result",
    "register_parenthood_domain",
    "review_developmental_stage_result",
    "select_journey_transfer_candidates",
    "validate_child_workspace",
    "validate_parenthood_memory_binding",
    "validate_parenthood_trace",
]
