"""Example LibCST transformer that appends a generated-code comment."""

import libcst as cst


class AppendCommentTransformer(cst.CSTTransformer):
    """Append a marker comment at the end of a module."""

    def leave_Module(
        self,
        original_node: cst.Module,
        updated_node: cst.Module,
    ) -> cst.Module:
        return updated_node.with_changes(
            footer=(
                *updated_node.footer,
                cst.EmptyLine(comment=cst.Comment("# Generated by CMM OS")),
            )
        )
