"""Phase 11.3 — Pydantic transport DTOs for the frozen v1 HTTP surface.

This module is the only place where the public application contracts meet
Pydantic.  It owns exactly two things:

- the request bodies of the v1 commands, bounded to the frozen public limits, so
  oversized or non-JSON input fails at transport parse rather than reaching
  orchestration;
- the public response envelopes and resource projections, which *re-validate*
  the application contracts' ``to_dict()`` output instead of re-implementing it.
  The application layer stays the owner of the public shape; a projection that
  drifts from the frozen v1 envelope fails loudly here rather than being served.

Phase 11.5 (DP-105) adds a third, strictly additive group: the transport DTOs of
the conversation surface.  They follow the same two rules for the canonical
conversational contracts — explicit caller-supplied identities, revisions and
timestamps in, re-validated ``to_dict()`` output out — and they carry no
conversational authority of their own.

Three boundaries are deliberate:

- ``idempotency_key`` is absent from every request body.  Idempotency is a
  header concern (``Idempotency-Key``) and the adapter maps it into the public
  application command, so a body can never open a second idempotency path;
- the safe metadata *grammar* (secret-shaped keys, binary data, unbounded
  nesting, non-finite numbers) is owned by ``cmm.application.contracts`` and is
  not duplicated here.  The transport bounds the container and leaves the
  grammar to its owner;
- every model is frozen and closed, so an unknown field or an API version the
  application layer does not serve can not be carried by a transport value.

See ``docs/reference/phase-11-application-backend.md``.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import (
    AfterValidator,
    BaseModel,
    ConfigDict,
    Field,
    JsonValue,
    StrictInt,
)

from cmm.application import (
    APPLICATION_API_VERSION,
    MAX_IDENTIFIER_LENGTH,
    MAX_MESSAGE_LENGTH,
    ApplicationCapability,
    ApplicationError,
    ApplicationErrorCode,
    ApplicationHealth,
    ApplicationResponse,
    ApplicationSession,
    ApplicationStatus,
    CapabilityStatus,
)
from cmm.conversation.contracts import (
    MAX_COLLECTION_ITEMS,
    MAX_STRING_LENGTH,
    AssistantResponse,
    ConversationCapabilityStatus,
    ConversationRole,
)
from cmm.conversation.state import ConversationState

__all__ = [
    "ApiVersion",
    "ApplicationCapabilityModel",
    "ApplicationErrorModel",
    "ApplicationHealthModel",
    "ApplicationResponseModel",
    "ApplicationSessionModel",
    "AssistantResponseModel",
    "ConversationAttachmentRefBody",
    "ConversationAttachmentRefModel",
    "ConversationCapabilityStateModel",
    "ConversationEditBody",
    "ConversationLineageModel",
    "ConversationMessageBody",
    "ConversationMessageModel",
    "ConversationRegenerateBody",
    "ConversationStateModel",
    "CreateSessionBody",
    "MessageBody",
    "assistant_response_model_from",
    "capability_model_from",
    "conversation_state_model_from",
    "error_model_from",
    "health_model_from",
    "response_model_from",
    "session_model_from",
]

#: The default public content type of a submitted message.
DEFAULT_CONTENT_TYPE = "text/plain"


def _supported_api_version(value: str) -> str:
    """Require the one public API version the application layer serves."""

    if value != APPLICATION_API_VERSION:
        raise ValueError(f"api_version must be {APPLICATION_API_VERSION!r}")
    return value


#: Transport view of the versioned public API identity.
ApiVersion = Annotated[str, AfterValidator(_supported_api_version)]


class _TransportModel(BaseModel):
    """Base of every transport DTO: closed, frozen and drift-rejecting."""

    model_config = ConfigDict(extra="forbid", frozen=True)


# ── Request bodies ───────────────────────────────────────────────────────────


class CreateSessionBody(_TransportModel):
    """Body of ``POST /v1/sessions``; the session identity is optional.

    An absent identifier asks the application layer to generate one, which is
    why the whole body may be omitted.  A present but empty identifier is
    malformed public input and fails closed.
    """

    session_id: str | None = Field(
        default=None, min_length=1, max_length=MAX_IDENTIFIER_LENGTH
    )


class MessageBody(_TransportModel):
    """Body of ``POST /v1/sessions/{session_id}/messages``.

    The session comes from the path and the idempotency key from the
    ``Idempotency-Key`` header, so neither is a body field.  An absent
    ``message_id`` is generated by the adapter and carried in the command
    payload.
    """

    message_id: str | None = Field(
        default=None, min_length=1, max_length=MAX_IDENTIFIER_LENGTH
    )
    actor_id: str = Field(min_length=1, max_length=MAX_IDENTIFIER_LENGTH)
    content: str = Field(min_length=1, max_length=MAX_MESSAGE_LENGTH)
    content_type: str = Field(
        default=DEFAULT_CONTENT_TYPE, min_length=1, max_length=MAX_IDENTIFIER_LENGTH
    )
    metadata: dict[str, JsonValue] = Field(default_factory=dict)
    # ``StrictInt`` keeps a caller defect out of the public contract: ``bool`` is
    # an ``int`` subclass, so a lax field would read ``True`` as revision ``1``.
    expected_session_revision: StrictInt | None = Field(default=None, ge=0)


# ── Response models ──────────────────────────────────────────────────────────


class ApplicationErrorModel(_TransportModel):
    """Transport view of one safe public application error."""

    code: ApplicationErrorCode
    message: str
    retryable: bool = False
    details: dict[str, JsonValue] = Field(default_factory=dict)


class ApplicationSessionModel(_TransportModel):
    """Transport view of one public session projection."""

    session_id: str
    revision: int
    status: str
    created_at: str
    updated_at: str


class ApplicationCapabilityModel(_TransportModel):
    """Transport view of one descriptive public capability declaration."""

    capability_id: str
    status: CapabilityStatus
    version: str
    operations: list[str] = Field(default_factory=list)
    reason_code: str | None = None


class ApplicationHealthModel(_TransportModel):
    """Transport view of the public readiness projection."""

    status: str
    api_version: ApiVersion
    platform_ready: bool
    services: list[str] = Field(default_factory=list)


class ApplicationResponseModel(_TransportModel):
    """The one public response envelope of the v1 surface.

    Success and failure share this envelope, so a client has exactly one public
    response shape and one deterministic JSON body to parse.
    """

    request_id: str
    api_version: ApiVersion
    status: ApplicationStatus
    data: dict[str, JsonValue] | None = None
    error: ApplicationErrorModel | None = None
    metadata: dict[str, JsonValue] = Field(default_factory=dict)


# ── Contract to transport conversion ─────────────────────────────────────────


def error_model_from(error: ApplicationError) -> ApplicationErrorModel:
    """Return the transport view of one safe public application error."""

    if not isinstance(error, ApplicationError):
        raise TypeError(
            f"error must be an ApplicationError, not {type(error).__name__}"
        )
    return ApplicationErrorModel.model_validate(error.to_dict())


def session_model_from(session: ApplicationSession) -> ApplicationSessionModel:
    """Return the transport view of one public session projection."""

    if not isinstance(session, ApplicationSession):
        raise TypeError(
            f"session must be an ApplicationSession, not {type(session).__name__}"
        )
    return ApplicationSessionModel.model_validate(session.to_dict())


def capability_model_from(
    capability: ApplicationCapability,
) -> ApplicationCapabilityModel:
    """Return the transport view of one public capability declaration."""

    if not isinstance(capability, ApplicationCapability):
        raise TypeError(
            "capability must be an ApplicationCapability, "
            f"not {type(capability).__name__}"
        )
    return ApplicationCapabilityModel.model_validate(capability.to_dict())


def health_model_from(health: ApplicationHealth) -> ApplicationHealthModel:
    """Return the transport view of the public readiness projection."""

    if not isinstance(health, ApplicationHealth):
        raise TypeError(
            f"health must be an ApplicationHealth, not {type(health).__name__}"
        )
    return ApplicationHealthModel.model_validate(health.to_dict())


def response_model_from(response: ApplicationResponse) -> ApplicationResponseModel:
    """Return the transport envelope for one public application response.

    The application contract owns the public shape: this only re-validates
    ``to_dict()``, so a drifted or unexpected projection is rejected at the
    transport boundary instead of being published as the v1 contract.
    """

    if not isinstance(response, ApplicationResponse):
        raise TypeError(
            f"response must be an ApplicationResponse, not {type(response).__name__}"
        )
    return ApplicationResponseModel.model_validate(response.to_dict())


# ── Conversational transport DTOs (Phase 11.5 / DP-105) ──────────────────────
#
# The additive conversation surface.  The adapter still owns no conversational
# authority: these DTOs carry the explicit identities, revision and timestamps
# the canonical conversational service requires — so the adapter invents no
# hidden state, owns no lineage and infers no authority from ``bot_id`` — and
# re-validate the canonical conversational contracts' ``to_dict()`` output
# instead of re-implementing it.

#: One bounded public conversational identifier inside a request body.
_ConversationIdentifier = Annotated[
    str, Field(min_length=1, max_length=MAX_IDENTIFIER_LENGTH)
]


class ConversationAttachmentRefBody(_TransportModel):
    """Body of one attachment reference of a submitted conversational turn.

    Attachments are references only: the transport carries the reference, its
    kind and the optional public display metadata — never content, never bytes
    and never a second file owner (Phase 11.5, DP-105).
    """

    ref: _ConversationIdentifier
    kind: _ConversationIdentifier
    name: str | None = Field(default=None, max_length=MAX_STRING_LENGTH)
    media_type: str | None = Field(default=None, max_length=MAX_STRING_LENGTH)


class _ConversationTurnBody(_TransportModel):
    """The explicit inputs shared by a submitted and an edited user turn.

    Every identity, the expected canonical revision and both timestamps are
    caller-supplied: the adapter generates none of them, exposes no ``lineage``
    field (the canonical service enforces lineage itself) and exposes no
    ``metadata`` field (the canonical session owns the committed transcript).
    ``content`` may be empty, exactly as the canonical conversational contract
    allows, so an attachment-only turn stays representable.
    """

    request_id: _ConversationIdentifier
    message_id: _ConversationIdentifier
    content: str = Field(max_length=MAX_MESSAGE_LENGTH)
    expected_session_revision: StrictInt = Field(ge=0)
    created_at: _ConversationIdentifier
    assistant_message_id: _ConversationIdentifier
    assistant_created_at: _ConversationIdentifier
    bot_id: _ConversationIdentifier | None = None
    requested_capabilities: list[_ConversationIdentifier] = Field(
        default_factory=list, max_length=MAX_COLLECTION_ITEMS
    )
    references: list[_ConversationIdentifier] = Field(
        default_factory=list, max_length=MAX_COLLECTION_ITEMS
    )
    attachments: list[ConversationAttachmentRefBody] = Field(
        default_factory=list, max_length=MAX_COLLECTION_ITEMS
    )


class ConversationMessageBody(_ConversationTurnBody):
    """Body of ``POST /v1/conversations/{session_id}/messages``.

    ``message_id`` is the identity of the submitted user message and the
    session is the path identity, so the adapter infers neither.
    """


class ConversationEditBody(_ConversationTurnBody):
    """Body of the conversational edit route.

    ``message_id`` is the identity of the *replacement* message; the edited
    original is the path identity.  The replacement carries no lineage: the
    canonical service binds the enforced ``supersedes_message_id`` itself.
    """


class ConversationRegenerateBody(_TransportModel):
    """Body of the conversational regeneration route.

    The target assistant response is the path identity and
    ``application_message_id`` is the new canonical application message
    identity the service re-runs; no new conversational user message is
    appended for it.
    """

    request_id: _ConversationIdentifier
    application_message_id: _ConversationIdentifier
    expected_session_revision: StrictInt = Field(ge=0)
    assistant_message_id: _ConversationIdentifier
    assistant_created_at: _ConversationIdentifier


class ConversationAttachmentRefModel(_TransportModel):
    """Transport view of one canonical conversational attachment reference."""

    ref: str
    kind: str
    name: str | None = None
    media_type: str | None = None


class ConversationLineageModel(_TransportModel):
    """Transport view of one canonical edit/regeneration lineage."""

    supersedes_message_id: str | None = None
    regenerates_message_id: str | None = None


class ConversationMessageModel(_TransportModel):
    """Transport view of one canonical conversational message."""

    id: str
    session_id: str
    role: ConversationRole
    content: str
    created_at: str
    bot_id: str | None = None
    references: list[str] = Field(default_factory=list)
    attachments: list[ConversationAttachmentRefModel] = Field(default_factory=list)
    lineage: ConversationLineageModel = Field(default_factory=ConversationLineageModel)
    metadata: dict[str, JsonValue] = Field(default_factory=dict)


class ConversationCapabilityStateModel(_TransportModel):
    """Transport view of one requested/effective capability declaration.

    The declaration is descriptive: a requested capability grants no authority.
    """

    capability: str
    requested: bool
    effective: str | None = None
    status: ConversationCapabilityStatus
    reason: str | None = None


class AssistantResponseModel(_TransportModel):
    """Transport view of one canonical ``AssistantResponse``.

    ``reasoning_summary`` is the canonical public explanation surface, never a
    hidden reasoning trace, and a reference is a public projection of a
    canonical owner rather than the owner itself.
    """

    message: ConversationMessageModel
    sources: list[str] = Field(default_factory=list)
    reasoning_summary: dict[str, JsonValue] = Field(default_factory=dict)
    pending_questions: list[str] = Field(default_factory=list)
    proposed_actions: list[str] = Field(default_factory=list)
    approval_requests: list[str] = Field(default_factory=list)
    workflow_updates: list[str] = Field(default_factory=list)
    domain_state: dict[str, JsonValue] = Field(default_factory=dict)
    capability_state: list[ConversationCapabilityStateModel] = Field(
        default_factory=list
    )
    memory_updates: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class ConversationStateModel(_TransportModel):
    """Transport view of the canonical conversational state of one session."""

    version: int
    session_id: str
    mode: str
    bot_id: str | None = None
    active_message_id: str | None = None
    messages: list[ConversationMessageModel] = Field(default_factory=list)


def assistant_response_model_from(
    response: AssistantResponse,
) -> AssistantResponseModel:
    """Return the transport view of one canonical conversational response.

    The conversational contract owns the public shape: this only re-validates
    ``to_dict()``, so a drifted or unexpected conversational projection is
    rejected at the transport boundary instead of being served as the
    conversation surface.
    """

    if not isinstance(response, AssistantResponse):
        raise TypeError(
            f"response must be an AssistantResponse, not {type(response).__name__}"
        )
    return AssistantResponseModel.model_validate(response.to_dict())


def conversation_state_model_from(state: ConversationState) -> ConversationStateModel:
    """Return the transport view of one canonical conversation state."""

    if not isinstance(state, ConversationState):
        raise TypeError(
            f"state must be a ConversationState, not {type(state).__name__}"
        )
    return ConversationStateModel.model_validate(state.to_dict())
