"""Phase 11.3 — Pydantic transport DTOs for the frozen v1 HTTP surface.

This module is the only place where the public application contracts meet
Pydantic.  It owns exactly two things:

- the request bodies of the v1 commands, bounded to the frozen public limits, so
  oversized or non-JSON input fails at transport parse rather than reaching
  orchestration;
- the public response envelopes and resource projections, which *re-validate*
  the application contracts' ``to_dict()`` output instead of re-implementing it.
  The application layer stays the owner of the public shape; a projection that
  drifts from the frozen v1 envelope fails loudly here rather than being served.

Three boundaries are deliberate:

- ``idempotency_key`` is absent from every request body.  Idempotency is a
  header concern (``Idempotency-Key``) and the adapter maps it into the public
  application command, so a body can never open a second idempotency path;
- the safe metadata *grammar* (secret-shaped keys, binary data, unbounded
  nesting, non-finite numbers) is owned by ``cmm.application.contracts`` and is
  not duplicated here.  The transport bounds the container and leaves the
  grammar to its owner;
- every model is frozen and closed, so an unknown field or an API version the
  application layer does not serve can not be carried by a transport value.

See ``docs/reference/phase-11-application-backend.md``.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import (
    AfterValidator,
    BaseModel,
    ConfigDict,
    Field,
    JsonValue,
    StrictInt,
)

from cmm.application import (
    APPLICATION_API_VERSION,
    MAX_IDENTIFIER_LENGTH,
    MAX_MESSAGE_LENGTH,
    ApplicationCapability,
    ApplicationError,
    ApplicationErrorCode,
    ApplicationHealth,
    ApplicationResponse,
    ApplicationSession,
    ApplicationStatus,
    CapabilityStatus,
)

__all__ = [
    "ApiVersion",
    "ApplicationCapabilityModel",
    "ApplicationErrorModel",
    "ApplicationHealthModel",
    "ApplicationResponseModel",
    "ApplicationSessionModel",
    "CreateSessionBody",
    "MessageBody",
    "capability_model_from",
    "error_model_from",
    "health_model_from",
    "response_model_from",
    "session_model_from",
]

#: The default public content type of a submitted message.
DEFAULT_CONTENT_TYPE = "text/plain"


def _supported_api_version(value: str) -> str:
    """Require the one public API version the application layer serves."""

    if value != APPLICATION_API_VERSION:
        raise ValueError(f"api_version must be {APPLICATION_API_VERSION!r}")
    return value


#: Transport view of the versioned public API identity.
ApiVersion = Annotated[str, AfterValidator(_supported_api_version)]


class _TransportModel(BaseModel):
    """Base of every transport DTO: closed, frozen and drift-rejecting."""

    model_config = ConfigDict(extra="forbid", frozen=True)


# ── Request bodies ───────────────────────────────────────────────────────────


class CreateSessionBody(_TransportModel):
    """Body of ``POST /v1/sessions``; the session identity is optional.

    An absent identifier asks the application layer to generate one, which is
    why the whole body may be omitted.  A present but empty identifier is
    malformed public input and fails closed.
    """

    session_id: str | None = Field(
        default=None, min_length=1, max_length=MAX_IDENTIFIER_LENGTH
    )


class MessageBody(_TransportModel):
    """Body of ``POST /v1/sessions/{session_id}/messages``.

    The session comes from the path and the idempotency key from the
    ``Idempotency-Key`` header, so neither is a body field.  An absent
    ``message_id`` is generated by the adapter and carried in the command
    payload.
    """

    message_id: str | None = Field(
        default=None, min_length=1, max_length=MAX_IDENTIFIER_LENGTH
    )
    actor_id: str = Field(min_length=1, max_length=MAX_IDENTIFIER_LENGTH)
    content: str = Field(min_length=1, max_length=MAX_MESSAGE_LENGTH)
    content_type: str = Field(
        default=DEFAULT_CONTENT_TYPE, min_length=1, max_length=MAX_IDENTIFIER_LENGTH
    )
    metadata: dict[str, JsonValue] = Field(default_factory=dict)
    # ``StrictInt`` keeps a caller defect out of the public contract: ``bool`` is
    # an ``int`` subclass, so a lax field would read ``True`` as revision ``1``.
    expected_session_revision: StrictInt | None = Field(default=None, ge=0)


# ── Response models ──────────────────────────────────────────────────────────


class ApplicationErrorModel(_TransportModel):
    """Transport view of one safe public application error."""

    code: ApplicationErrorCode
    message: str
    retryable: bool = False
    details: dict[str, JsonValue] = Field(default_factory=dict)


class ApplicationSessionModel(_TransportModel):
    """Transport view of one public session projection."""

    session_id: str
    revision: int
    status: str
    created_at: str
    updated_at: str


class ApplicationCapabilityModel(_TransportModel):
    """Transport view of one descriptive public capability declaration."""

    capability_id: str
    status: CapabilityStatus
    version: str
    operations: list[str] = Field(default_factory=list)
    reason_code: str | None = None


class ApplicationHealthModel(_TransportModel):
    """Transport view of the public readiness projection."""

    status: str
    api_version: ApiVersion
    platform_ready: bool
    services: list[str] = Field(default_factory=list)


class ApplicationResponseModel(_TransportModel):
    """The one public response envelope of the v1 surface.

    Success and failure share this envelope, so a client has exactly one public
    response shape and one deterministic JSON body to parse.
    """

    request_id: str
    api_version: ApiVersion
    status: ApplicationStatus
    data: dict[str, JsonValue] | None = None
    error: ApplicationErrorModel | None = None
    metadata: dict[str, JsonValue] = Field(default_factory=dict)


# ── Contract to transport conversion ─────────────────────────────────────────


def error_model_from(error: ApplicationError) -> ApplicationErrorModel:
    """Return the transport view of one safe public application error."""

    if not isinstance(error, ApplicationError):
        raise TypeError(
            f"error must be an ApplicationError, not {type(error).__name__}"
        )
    return ApplicationErrorModel.model_validate(error.to_dict())


def session_model_from(session: ApplicationSession) -> ApplicationSessionModel:
    """Return the transport view of one public session projection."""

    if not isinstance(session, ApplicationSession):
        raise TypeError(
            f"session must be an ApplicationSession, not {type(session).__name__}"
        )
    return ApplicationSessionModel.model_validate(session.to_dict())


def capability_model_from(
    capability: ApplicationCapability,
) -> ApplicationCapabilityModel:
    """Return the transport view of one public capability declaration."""

    if not isinstance(capability, ApplicationCapability):
        raise TypeError(
            "capability must be an ApplicationCapability, "
            f"not {type(capability).__name__}"
        )
    return ApplicationCapabilityModel.model_validate(capability.to_dict())


def health_model_from(health: ApplicationHealth) -> ApplicationHealthModel:
    """Return the transport view of the public readiness projection."""

    if not isinstance(health, ApplicationHealth):
        raise TypeError(
            f"health must be an ApplicationHealth, not {type(health).__name__}"
        )
    return ApplicationHealthModel.model_validate(health.to_dict())


def response_model_from(response: ApplicationResponse) -> ApplicationResponseModel:
    """Return the transport envelope for one public application response.

    The application contract owns the public shape: this only re-validates
    ``to_dict()``, so a drifted or unexpected projection is rejected at the
    transport boundary instead of being published as the v1 contract.
    """

    if not isinstance(response, ApplicationResponse):
        raise TypeError(
            f"response must be an ApplicationResponse, not {type(response).__name__}"
        )
    return ApplicationResponseModel.model_validate(response.to_dict())
