from __future__ import annotations

from dataclasses import FrozenInstanceError
from pathlib import Path
from tempfile import TemporaryDirectory

import libcst as cst
import pytest

from cmm.execution.python import (
    PythonModuleEditor,
    PythonModuleInfo,
    PythonModuleWriter,
)
from cmm.execution.python.visitors import AppendCommentTransformer


def _module_info(path: Path, code: str = "value = 1\n") -> PythonModuleInfo:
    return PythonModuleInfo(
        path=path,
        module_name=path.stem,
        parsed_module=cst.parse_module(code),
    )


def test_editor_is_immutable() -> None:
    module_info = _module_info(Path("module.py"))
    editor = PythonModuleEditor(module_info)

    with pytest.raises(FrozenInstanceError):
        editor.module_info = module_info


def test_apply_returns_new_module_info_without_changing_original() -> None:
    module_info = _module_info(Path("module.py"))
    editor = PythonModuleEditor(module_info)

    updated_module_info = editor.apply(AppendCommentTransformer())

    assert updated_module_info is not module_info
    assert module_info.parsed_module is not updated_module_info.parsed_module
    assert module_info.parsed_module.code == "value = 1\n"
    assert updated_module_info.parsed_module.code.endswith("# Generated by CMM OS\n")


def test_writer_persists_changed_module_code() -> None:
    with TemporaryDirectory() as directory:
        module_path = Path(directory) / "module.py"
        module_path.write_text("value = 1\n", encoding="utf-8")
        module_info = _module_info(module_path)
        updated_module_info = PythonModuleEditor(module_info).apply(
            AppendCommentTransformer()
        )

        wrote = PythonModuleWriter().write(updated_module_info)

        assert wrote
        assert module_path.read_text(encoding="utf-8") == updated_module_info.parsed_module.code


def test_writer_avoids_unnecessary_write_for_identical_code() -> None:
    with TemporaryDirectory() as directory:
        module_path = Path(directory) / "module.py"
        module_path.write_text("value = 1\n", encoding="utf-8")

        wrote = PythonModuleWriter().write(_module_info(module_path))

        assert not wrote
        assert module_path.read_text(encoding="utf-8") == "value = 1\n"
