"""Phase 9 – Autonomous Agent Runtime Package.

Exports foundational contracts, enums, errors, goal system, intake, and Phase 9.4 Observation Engine.
"""

from cmm.agent_runtime.contracts import (
    AgentDefinition,
    AgentResult,
    AgentRun,
    RuntimeDecision,
)
from cmm.agent_runtime.enums import (
    AgentResultOutcome,
    AgentRuntimeStatus,
    GoalAmbiguityKind,
    GoalConstraintKind,
    GoalDependencyType,
    GoalIntakeDecisionType,
    GoalKind,
    GoalProposalStatus,
    GoalSource,
    GoalStatus,
    ObservationKind,
    ObservationSignificance,
    ObservationStatus,
    ObservedChangeKind,
    ObserverStatus,
    RuntimeDecisionType,
    Significance,
    SuccessCriterionKind,
    SuccessCriterionStatus,
)
from cmm.agent_runtime.errors import (
    AgentRuntimeError,
    DuplicateGoalError,
    DuplicateObserverError,
    GoalCompletionError,
    GoalDependencyError,
    GoalError,
    GoalIntakeError,
    GoalNormalizationError,
    GoalNotFoundError,
    GoalProposalConversionError,
    GoalProposalNotFoundError,
    GoalProposalStateError,
    InvalidAgentContractError,
    InvalidAgentIdentifierError,
    InvalidGoalContractError,
    InvalidGoalProposalError,
    InvalidGoalTransitionError,
    InvalidObservationContractError,
    ObservationEngineError,
    ObservationPermissionError,
    ObservationTimeoutError,
    ObserverDisabledError,
    ObserverExecutionError,
    ObserverNotFoundError,
)
from cmm.agent_runtime.goal_contracts import (
    Goal,
    GoalConstraint,
    GoalDependency,
    GoalHistoryEntry,
    GoalPriority,
    GoalQuery,
    GoalSearchResult,
    SuccessCriterion,
)
from cmm.agent_runtime.goal_intake_contracts import (
    GoalAmbiguity,
    GoalInformationGap,
    GoalIntakeDecision,
    GoalNormalizationRequest,
    GoalNormalizationResult,
    GoalProposal,
    GoalProposalQuery,
)
from cmm.agent_runtime.goal_intake_repository import (
    GoalProposalRepository,
    InMemoryGoalProposalRepository,
)
from cmm.agent_runtime.goal_intake_service import (
    DeterministicGoalNormalizer,
    GoalIntakeService,
    GoalNormalizer,
)
from cmm.agent_runtime.goal_manager import GoalManager
from cmm.agent_runtime.goal_repository import GoalRepository, InMemoryGoalRepository
from cmm.agent_runtime.observation_cognitive_adapter import ObservationResourceAdapter
from cmm.agent_runtime.observation_contracts import (
    Observation,
    ObservationError,
    ObservationQuery,
    ObservationRequest,
    ObservationResult,
    ObservationSnapshot,
    ObservationSourceVersion,
    ObservedChange,
)
from cmm.agent_runtime.observation_diff import compare_snapshots
from cmm.agent_runtime.observation_engine import ObservationEngine
from cmm.agent_runtime.observation_observers import (
    GitObserver,
    GoalObserver,
    MemoryObserver,
    RepositoryObserver,
    SystemHealthObserver,
    ValidationObserver,
)
from cmm.agent_runtime.observer_protocol import Observer, ObserverMetadataMixin
from cmm.agent_runtime.observer_registry import ObserverRegistry

__all__ = [
    "AgentDefinition",
    "AgentResult",
    "AgentResultOutcome",
    "AgentRun",
    "AgentRuntimeError",
    "AgentRuntimeStatus",
    "DeterministicGoalNormalizer",
    "DuplicateGoalError",
    "DuplicateObserverError",
    "GitObserver",
    "Goal",
    "GoalAmbiguity",
    "GoalAmbiguityKind",
    "GoalCompletionError",
    "GoalConstraint",
    "GoalConstraintKind",
    "GoalDependency",
    "GoalDependencyError",
    "GoalDependencyType",
    "GoalError",
    "GoalHistoryEntry",
    "GoalInformationGap",
    "GoalIntakeDecision",
    "GoalIntakeDecisionType",
    "GoalIntakeError",
    "GoalIntakeService",
    "GoalKind",
    "GoalManager",
    "GoalNormalizationError",
    "GoalNormalizationRequest",
    "GoalNormalizationResult",
    "GoalNormalizer",
    "GoalNotFoundError",
    "GoalObserver",
    "GoalPriority",
    "GoalProposal",
    "GoalProposalConversionError",
    "GoalProposalNotFoundError",
    "GoalProposalQuery",
    "GoalProposalRepository",
    "GoalProposalStateError",
    "GoalProposalStatus",
    "GoalQuery",
    "GoalRepository",
    "GoalSearchResult",
    "GoalSource",
    "GoalStatus",
    "InMemoryGoalProposalRepository",
    "InMemoryGoalRepository",
    "InvalidAgentContractError",
    "InvalidAgentIdentifierError",
    "InvalidGoalContractError",
    "InvalidGoalProposalError",
    "InvalidGoalTransitionError",
    "InvalidObservationContractError",
    "MemoryObserver",
    "Observation",
    "ObservationEngine",
    "ObservationEngineError",
    "ObservationError",
    "ObservationKind",
    "ObservationPermissionError",
    "ObservationQuery",
    "ObservationRequest",
    "ObservationResourceAdapter",
    "ObservationResult",
    "ObservationSignificance",
    "ObservationSnapshot",
    "ObservationSourceVersion",
    "ObservationStatus",
    "ObservationTimeoutError",
    "ObservedChange",
    "ObservedChangeKind",
    "Observer",
    "ObserverDisabledError",
    "ObserverExecutionError",
    "ObserverMetadataMixin",
    "ObserverNotFoundError",
    "ObserverRegistry",
    "ObserverStatus",
    "RepositoryObserver",
    "RuntimeDecision",
    "RuntimeDecisionType",
    "Significance",
    "SuccessCriterion",
    "SuccessCriterionKind",
    "SuccessCriterionStatus",
    "SystemHealthObserver",
    "ValidationObserver",
    "compare_snapshots",
]
