"""Phase 9 – Autonomous Agent Runtime Package.

Exports foundational contracts, enums, errors, repository, and GoalManager for Phase 9.1 and Phase 9.2.
"""

from cmm.agent_runtime.contracts import (
    AgentDefinition,
    AgentResult,
    AgentRun,
    RuntimeDecision,
)
from cmm.agent_runtime.enums import (
    AgentResultOutcome,
    AgentRuntimeStatus,
    GoalAmbiguityKind,
    GoalConstraintKind,
    GoalDependencyType,
    GoalIntakeDecisionType,
    GoalKind,
    GoalProposalStatus,
    GoalSource,
    GoalStatus,
    RuntimeDecisionType,
    SuccessCriterionKind,
    SuccessCriterionStatus,
)
from cmm.agent_runtime.errors import (
    AgentRuntimeError,
    DuplicateGoalError,
    GoalCompletionError,
    GoalDependencyError,
    GoalError,
    GoalIntakeError,
    GoalNormalizationError,
    GoalNotFoundError,
    GoalProposalConversionError,
    GoalProposalNotFoundError,
    GoalProposalStateError,
    InvalidAgentContractError,
    InvalidAgentIdentifierError,
    InvalidGoalContractError,
    InvalidGoalProposalError,
    InvalidGoalTransitionError,
)
from cmm.agent_runtime.goal_contracts import (
    Goal,
    GoalConstraint,
    GoalDependency,
    GoalHistoryEntry,
    GoalPriority,
    GoalQuery,
    GoalSearchResult,
    SuccessCriterion,
)
from cmm.agent_runtime.goal_intake_contracts import (
    GoalAmbiguity,
    GoalInformationGap,
    GoalIntakeDecision,
    GoalNormalizationRequest,
    GoalNormalizationResult,
    GoalProposal,
    GoalProposalQuery,
)
from cmm.agent_runtime.goal_intake_repository import (
    GoalProposalRepository,
    InMemoryGoalProposalRepository,
)
from cmm.agent_runtime.goal_intake_service import (
    DeterministicGoalNormalizer,
    GoalIntakeService,
    GoalNormalizer,
)
from cmm.agent_runtime.goal_manager import GoalManager
from cmm.agent_runtime.goal_repository import GoalRepository, InMemoryGoalRepository

__all__ = [
    "AgentDefinition",
    "AgentResult",
    "AgentResultOutcome",
    "AgentRun",
    "AgentRuntimeError",
    "AgentRuntimeStatus",
    "DeterministicGoalNormalizer",
    "DuplicateGoalError",
    "Goal",
    "GoalAmbiguity",
    "GoalAmbiguityKind",
    "GoalCompletionError",
    "GoalConstraint",
    "GoalConstraintKind",
    "GoalDependency",
    "GoalDependencyError",
    "GoalDependencyType",
    "GoalError",
    "GoalHistoryEntry",
    "GoalInformationGap",
    "GoalIntakeDecision",
    "GoalIntakeDecisionType",
    "GoalIntakeError",
    "GoalIntakeService",
    "GoalKind",
    "GoalManager",
    "GoalNormalizationError",
    "GoalNormalizationRequest",
    "GoalNormalizationResult",
    "GoalNormalizer",
    "GoalNotFoundError",
    "GoalPriority",
    "GoalProposal",
    "GoalProposalConversionError",
    "GoalProposalNotFoundError",
    "GoalProposalQuery",
    "GoalProposalRepository",
    "GoalProposalStateError",
    "GoalProposalStatus",
    "GoalQuery",
    "GoalRepository",
    "GoalSearchResult",
    "GoalSource",
    "GoalStatus",
    "InMemoryGoalProposalRepository",
    "InMemoryGoalRepository",
    "InvalidAgentContractError",
    "InvalidAgentIdentifierError",
    "InvalidGoalContractError",
    "InvalidGoalProposalError",
    "InvalidGoalTransitionError",
    "RuntimeDecision",
    "RuntimeDecisionType",
    "SuccessCriterion",
    "SuccessCriterionKind",
    "SuccessCriterionStatus",
]
