"""Phase 10.24 — Reflection Domain Profile.

A deliberately conservative ``DomainProfileDefinition`` for reflective
reasoning: high sensitivity, prudent inference depth, multiple hypotheses,
retained open questions, no forced conclusion, restricted identity inference,
confirmation-gated semantic persistence, and no automatic personal decision.
It configures shared cognition through the shared profile contracts; it does
not create a cognitive engine.
"""

from __future__ import annotations

from cmm.cognitive.enums import SensitivityLevel
from cmm.domains.enums import DomainReasoningDepth
from cmm.domains.profile_contracts import (
    DomainMemoryPolicy,
    DomainPresentationPolicy,
    DomainProductionPolicy,
    DomainProfileDefinition,
    DomainQuestionPolicy,
    DomainTemporalPolicy,
)
from cmm.domains.reflection.catalog import CANONICAL_REFLECTION_RULE_IDS
from cmm.domains.reflection.resources import REFLECTION_RESOURCE_KINDS

REFLECTION_PROFILE_ID = "reflection.profile"
REFLECTION_PROFILE_NAME = "ReflectionProfile"

# Forbidden autonomous actions of the Reflection safety model (spec §15, §19,
# §22, §23).
REFLECTION_PROHIBITED_ACTIONS: tuple[str, ...] = (
    "personal_decision_adoption",
    "decision_adoption",
    "strategy_adoption",
    "semantic_memory_write",
    "memory_persistence",
    "unconfirmed_memory_persistence",
    "unconfirmed_interest_persistence",
    "identity_classification",
    "identity_persistence",
    "diagnosis_presentation",
    "no_diagnosis_presentation",
    "psychological_diagnosis",
    "notion_write",
    "notion_page_creation",
    "notion_page_update",
    "external_communication",
    "message_send",
    "email_send",
    "calendar_modification",
    "task_creation",
    "schedule_modification",
    "content_publication",
    "purchase",
    "form_submission",
    "knowledge_delete",
    "export",
    "shell_execution",
    "sensitive_inference_persist",
)


def build_reflection_profile() -> DomainProfileDefinition:
    """Build the ``ReflectionProfile`` deterministically."""
    return DomainProfileDefinition(
        id=REFLECTION_PROFILE_ID,
        domain_id="domain:reflection",
        profile_name=REFLECTION_PROFILE_NAME,
        required_rules=CANONICAL_REFLECTION_RULE_IDS,
        optional_rules=(),
        prohibited_rules=(),
        allowed_resource_kinds=REFLECTION_RESOURCE_KINDS,
        priority_resource_kinds=(),
        prohibited_resource_kinds=(),
        minimum_confidence=0.6,
        reasoning_depth=DomainReasoningDepth.STANDARD,
        allowed_inferences=(
            "observation",
            "user_stated_narrative",
            "interpretation",
            "experience",
            "belief_candidate",
            "value_candidate",
            "emotion_candidate",
            "need_candidate",
            "contradiction",
            "ambivalence",
            "multiple_hypotheses",
            "counter_hypothesis",
            "no_forced_conclusion",
            "uncertainty",
            "open_question",
            "missing_information",
            "temporal_state",
            "temporally_ambiguous",
            "interest_candidate",
            "interest_provenance",
            "hypothetical_identity_narrative",
            "identity_narrative_version",
            "decision_review",
            "decision_candidate",
            "proposal",
            "prepared_content",
            "confirmed_persistence_proposal",
            "future_behavior_unknowable",
        ),
        prohibited_inferences=(
            "identity_classification",
            "personality_classification",
            "sexual_identity_inference",
            "political_identity_inference",
            "religious_identity_inference",
            "attachment_classification",
            "mental_disorder_diagnosis",
            "psychological_diagnosis",
            "moral_character_inference",
            "fixed_motive_inference",
            "identity_fact_inference",
            "interest_identity_inference",
            "interest_commitment_inference",
            "confirmed_persistence_inference",
            "decision_adoption",
            "personal_decision_inference",
            "sensitive_inference_persist",
        ),
        maximum_questions=10,
        escalation_rules=(
            "reflection.multiple_hypotheses",
            "reflection.no_forced_conclusion",
            "reflection.open_question",
        ),
        prohibited_actions=REFLECTION_PROHIBITED_ACTIONS,
        question_policy=DomainQuestionPolicy(
            maximum_questions=10,
            allow_follow_up=True,
            require_deduplication=True,
            allow_clarification=True,
            stop_on_blocking_gap=True,
        ),
        presentation_policy=DomainPresentationPolicy(
            detail_level="detailed",
            include_uncertainty=True,
            include_provenance=True,
            include_alternatives=True,
            allow_speculation=False,
            require_disclaimers=True,
            required_sections=(
                "observations",
                "interpretations",
                "beliefs",
                "values",
                "emotions",
                "needs",
                "hypotheses",
                "counter_hypotheses",
                "evidence",
                "counterevidence",
                "uncertainty",
                "ambivalence",
                "conflicts",
                "open_questions",
                "temporal_state",
                "interest_provenance",
                "persistence_state",
                "decision_state",
                "sources",
            ),
            optional_sections=("timeline", "comparison", "summary"),
            suppressible_sections=(),
            preferred_section_order=(
                "observations",
                "interpretations",
                "beliefs",
                "values",
                "emotions",
                "needs",
                "hypotheses",
                "counter_hypotheses",
                "evidence",
                "counterevidence",
                "uncertainty",
                "ambivalence",
                "conflicts",
                "open_questions",
                "temporal_state",
                "interest_provenance",
                "persistence_state",
                "decision_state",
                "sources",
            ),
            protected_terms=(
                "observation",
                "interpretation",
                "belief",
                "hypothesis",
                "counter_hypothesis",
                "uncertainty",
                "ambivalence",
                "open_question",
                "temporally_ambiguous",
                "interest_candidate",
                "persistent_confirmed",
                "pending_confirmation",
                "decision_candidate",
                "proposal",
                "prepared_content",
                "not_diagnosis",
                "hypothetical",
                "identity_narrative",
            ),
            term_glosses={
                "observation": "directly evidenced statement",
                "interpretation": "user's or system interpretation, not a fact",
                "belief": "belief candidate, not a verified fact",
                "hypothesis": "unverified system proposition",
                "counter_hypothesis": "alternative unverified proposition",
                "uncertainty": "unknown confidence",
                "ambivalence": "simultaneous valid conflicting states",
                "open_question": "question unresolved by the current basis",
                "temporally_ambiguous": "chronology cannot be established",
                "interest_candidate": "possible interest, not confirmed persistence",
                "persistent_confirmed": "persistence confirmed through a valid mechanism",
                "pending_confirmation": "persistence waits for user confirmation",
                "decision_candidate": "candidate, not an adopted decision",
                "proposal": "a candidate, not an adopted decision or action",
                "prepared_content": "preparation only, no external write",
                "not_diagnosis": "psychological hypothesis, never a diagnosis",
                "hypothetical": "hypothetical inference, reversible and unpersisted",
                "identity_narrative": "user-provided narrative, not a stable identity fact",
            },
            preferred_components=(
                "observations",
                "interpretations",
                "beliefs",
                "hypotheses",
                "open_questions",
                "uncertainty",
            ),
            preferred_views=("structured",),
            warning_position="before_content",
            allowed_output_types=("HUMAN_READABLE", "STRUCTURED"),
            preferred_output_types=("STRUCTURED",),
        ),
        memory_policy=DomainMemoryPolicy(
            allow_read=True,
            allow_write=False,
            allow_long_term=False,
            allow_cross_domain=False,
            retention_scope="session",
            sensitivity_limit=SensitivityLevel.HIGHLY_SENSITIVE,
        ),
        temporal_policy=DomainTemporalPolicy(
            require_current_information=False,
            allow_historical_information=True,
            require_temporal_provenance=True,
            allow_future_projection=False,
        ),
        production_policy=DomainProductionPolicy(
            allow_draft=True,
            allow_final=False,
            allow_external_action=False,
            require_review=True,
            require_validation=True,
            maximum_output_items=64,
        ),
        permissions=(
            "resource.read",
            "memory.read",
            "operation.execute",
        ),
        metadata={"phase": "10.24"},
    )


__all__ = [
    "REFLECTION_PROFILE_ID",
    "REFLECTION_PROFILE_NAME",
    "REFLECTION_PROHIBITED_ACTIONS",
    "build_reflection_profile",
]