"""Configurable planning providers for supervised development."""

from __future__ import annotations

import importlib
import json
import os
import re
from typing import Any, Mapping, Protocol, runtime_checkable

from cmm.development.analyzer import ProjectContext
from cmm.development.models import DevelopmentPlan, PlanValidationError
from kernel.llm.exceptions import ProviderError
from kernel.llm.models import LLMRequest
from kernel.llm.openai_provider import OpenAIProvider


class PlanningProviderError(RuntimeError):
    """Raised when a planning provider cannot produce a usable plan."""


@runtime_checkable
class PlanningProvider(Protocol):
    def generate_plan(self, goal: str, context: ProjectContext) -> DevelopmentPlan | Mapping[str, Any]:
        """Return a structured development plan for the goal and project context."""


class DeterministicPlanningProvider:
    """Small deterministic provider for automation and explicit goals."""

    def __init__(
        self,
        plan: DevelopmentPlan | Mapping[str, Any] | None = None,
        *,
        plans: list[DevelopmentPlan | Mapping[str, Any]] | None = None,
        corrections: list[DevelopmentPlan | Mapping[str, Any]] | None = None,
    ) -> None:
        self._plan = plan
        self._plans = list(plans or [])
        self._corrections = list(corrections or [])

    def generate_plan(self, goal: str, context: ProjectContext) -> DevelopmentPlan | Mapping[str, Any]:
        if self._plans:
            return self._plans.pop(0)
        if self._plan is not None:
            return self._plan
        stripped = goal.strip()
        if stripped.startswith("{"):
            try:
                payload = json.loads(stripped)
            except json.JSONDecodeError as error:
                raise PlanningProviderError(f"Invalid JSON development goal: {error}") from error
            if not isinstance(payload, Mapping):
                raise PlanningProviderError("A JSON development goal must contain a plan object.")
            return payload

        match = re.fullmatch(
            r"create\s+class\s+(?P<class>[A-Za-z_]\w*)\s+in\s+(?P<path>\S+\.py)",
            stripped,
            flags=re.IGNORECASE,
        )
        if match:
            path = match.group("path")
            operations = []
            if path not in {item.path for item in context.files}:
                operations.append(
                    {
                        "domain": "filesystem",
                        "type": "write_file",
                        "parameters": {"path": path, "content": "# Generated by CMM OS.\n"},
                        "reason": "Create the requested Python module before editing it semantically.",
                    }
                )
            operations.append(
                {
                    "domain": "python",
                    "type": "create_class",
                    "parameters": {"path": path, "class_name": match.group("class")},
                    "reason": "Create the explicitly requested class.",
                }
            )
            return {
                "goal": goal,
                "affected_files": [path],
                "operations": operations,
                "rationale": "Deterministic plan derived from the explicit class creation goal.",
                "validations": ["python_ast", "python_compile"],
                "risks": [],
            }
        raise PlanningProviderError(
            "The deterministic provider accepts a structured JSON plan or "
            "'create class <Name> in <path.py>'. Select --provider ollama for free-form goals."
        )

    def generate_correction(self, goal, context, previous_plan, previous_result, failure):
        """Return a queued correction for deterministic cycle tests and automation."""

        if self._corrections:
            return self._corrections.pop(0)
        return None



class OpenAIPlanningProvider:
    """Planning adapter backed by the shared kernel OpenAI provider."""

    def __init__(
        self,
        model: str | None = None,
        *,
        provider: OpenAIProvider | None = None,
    ) -> None:
        self.model = model or os.getenv("OPENAI_MODEL", "gpt-5-mini")
        self.provider = provider or OpenAIProvider(model=self.model)

    def generate_plan(
        self,
        goal: str,
        context: ProjectContext,
    ) -> Mapping[str, Any]:
        request = LLMRequest(
            prompt=self._prompt(goal, context),
            system_prompt=(
                "You are the planning provider for CMM OS. "
                "Return exactly one valid JSON object. "
                "Use only project-relative paths and registered semantic operations. "
                "Preserve every explicit file path from the user goal exactly. "
                "Never emit Markdown, shell commands, or explanatory text."
            ),
            temperature=0.0,
        )

        try:
            response = self.provider.generate(request)
            payload = json.loads(response.content)
        except ProviderError as error:
            raise PlanningProviderError(str(error)) from error
        except json.JSONDecodeError as error:
            raise PlanningProviderError(
                f"OpenAI returned invalid JSON: {error}"
            ) from error

        if not isinstance(payload, Mapping):
            raise PlanningProviderError(
                "OpenAI returned a JSON value that is not a plan object."
            )

        self._validate_explicit_path(goal, payload)
        return payload

    def _validate_explicit_path(
        self,
        goal: str,
        payload: Mapping[str, Any],
    ) -> None:
        """Reject plans that replace an explicitly requested Python path."""

        match = re.search(
            r"\bin\s+(?P<path>[^\s]+\.py)\b",
            goal,
            flags=re.IGNORECASE,
        )
        if match is None:
            return

        requested_path = match.group("path")
        affected_files = payload.get("affected_files", [])
        operations = payload.get("operations", [])

        operation_paths = {
            str(parameters["path"])
            for operation in operations
            if isinstance(operation, Mapping)
            for parameters in [operation.get("parameters")]
            if isinstance(parameters, Mapping) and "path" in parameters
        }

        if requested_path not in affected_files or requested_path not in operation_paths:
            raise PlanningProviderError(
                "OpenAI changed an explicitly requested path: "
                f"expected '{requested_path}'."
            )

    def _prompt(self, goal: str, context: ProjectContext) -> str:
        schema = {
            "goal": goal,
            "affected_files": ["relative/path.py"],
            "operations": [
                {
                    "domain": "python",
                    "type": "create_class",
                    "parameters": {
                        "path": "relative/path.py",
                        "class_name": "Name",
                    },
                    "reason": "brief reason",
                }
            ],
            "rationale": "brief rationale",
            "validations": ["python_ast", "python_compile"],
            "risks": [],
        }

        return (
            "Generate one development plan matching this schema:\n"
            f"{json.dumps(schema, ensure_ascii=True)}\n"
            "Rules:\n"
            "- Preserve all file paths explicitly written in the goal exactly.\n"
            "- Do not relocate requested files into another directory.\n"
            "- Use only project-relative paths.\n"
            "- Return JSON only.\n"
            "Available project context:\n"
            f"{json.dumps(context.serialize(), ensure_ascii=True)}\n"
            f"Development goal: {goal}"
        )


class OllamaPlanningProvider:
    """Optional Ollama provider whose dependency is loaded only when used."""

    def __init__(self, model: str = "qwen2.5-coder:7b") -> None:
        self.model = model

    def generate_plan(self, goal: str, context: ProjectContext) -> Mapping[str, Any]:
        try:
            ollama = importlib.import_module("ollama")
        except ImportError as error:
            raise PlanningProviderError(
                "Ollama provider requested, but the optional 'ollama' package is not installed."
            ) from error

        prompt = self._prompt(goal, context)
        try:
            response = ollama.chat(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                format="json",
            )
            content = self._response_content(response)
            payload = json.loads(content)
        except (AttributeError, KeyError, json.JSONDecodeError, TypeError, ValueError) as error:
            raise PlanningProviderError(f"Ollama returned an invalid structured plan: {error}") from error
        if not isinstance(payload, Mapping):
            raise PlanningProviderError("Ollama returned a JSON value that is not a plan object.")
        return payload

    def _response_content(self, response: Any) -> str:
        """Read both Ollama client's object and dictionary response shapes."""

        if isinstance(response, Mapping):
            message = response["message"]
            if isinstance(message, Mapping):
                return str(message["content"])
            return str(getattr(message, "content"))
        return str(response.message.content)

    def _prompt(self, goal: str, context: ProjectContext) -> str:
        schema = {
            "goal": goal,
            "affected_files": ["relative/path.py"],
            "operations": [
                {
                    "domain": "python",
                    "type": "create_class",
                    "parameters": {"path": "relative/path.py", "class_name": "Name"},
                    "reason": "brief reason",
                }
            ],
            "rationale": "brief rationale",
            "validations": ["python_ast", "python_compile"],
            "risks": [],
        }
        return (
            "Produce only one JSON object matching this schema. Use only project-relative paths and "
            "CMM semantic operations; do not emit shell commands.\n"
            f"Schema example: {json.dumps(schema, ensure_ascii=True)}\n"
            f"Project context: {json.dumps(context.serialize(), ensure_ascii=True)}\n"
            f"Goal: {goal}"
        )


def create_planning_provider(name: str) -> PlanningProvider:
    """Resolve a provider name from the CLI without importing optional dependencies."""

    provider_name, separator, model = name.partition(":")
    if provider_name == "deterministic":
        if separator:
            raise PlanValidationError("The deterministic provider does not accept a model suffix.")
        return DeterministicPlanningProvider()
    if provider_name == "ollama":
        return OllamaPlanningProvider(model or "qwen2.5-coder:7b")
    if provider_name == "openai":
        return OpenAIPlanningProvider(model or None)
    raise PlanValidationError(f"Unknown planning provider: {name}")
