"""Configurable planning providers for supervised development."""

from __future__ import annotations

import importlib
import json
import re
from typing import Any, Mapping, Protocol, runtime_checkable

from cmm.development.analyzer import ProjectContext
from cmm.development.models import DevelopmentPlan, PlanValidationError


class PlanningProviderError(RuntimeError):
    """Raised when a planning provider cannot produce a usable plan."""


@runtime_checkable
class PlanningProvider(Protocol):
    def generate_plan(self, goal: str, context: ProjectContext) -> DevelopmentPlan | Mapping[str, Any]:
        """Return a structured development plan for the goal and project context."""


class DeterministicPlanningProvider:
    """Small deterministic provider for automation and explicit goals."""

    def __init__(
        self,
        plan: DevelopmentPlan | Mapping[str, Any] | None = None,
        *,
        plans: list[DevelopmentPlan | Mapping[str, Any]] | None = None,
        corrections: list[DevelopmentPlan | Mapping[str, Any]] | None = None,
    ) -> None:
        self._plan = plan
        self._plans = list(plans or [])
        self._corrections = list(corrections or [])

    def generate_plan(self, goal: str, context: ProjectContext) -> DevelopmentPlan | Mapping[str, Any]:
        if self._plans:
            return self._plans.pop(0)
        if self._plan is not None:
            return self._plan
        stripped = goal.strip()
        if stripped.startswith("{"):
            try:
                payload = json.loads(stripped)
            except json.JSONDecodeError as error:
                raise PlanningProviderError(f"Invalid JSON development goal: {error}") from error
            if not isinstance(payload, Mapping):
                raise PlanningProviderError("A JSON development goal must contain a plan object.")
            return payload

        match = re.fullmatch(
            r"create\s+class\s+(?P<class>[A-Za-z_]\w*)\s+in\s+(?P<path>\S+\.py)",
            stripped,
            flags=re.IGNORECASE,
        )
        if match:
            path = match.group("path")
            operations = []
            if path not in {item.path for item in context.files}:
                operations.append(
                    {
                        "domain": "filesystem",
                        "type": "write_file",
                        "parameters": {"path": path, "content": "# Generated by CMM OS.\n"},
                        "reason": "Create the requested Python module before editing it semantically.",
                    }
                )
            operations.append(
                {
                    "domain": "python",
                    "type": "create_class",
                    "parameters": {"path": path, "class_name": match.group("class")},
                    "reason": "Create the explicitly requested class.",
                }
            )
            return {
                "goal": goal,
                "affected_files": [path],
                "operations": operations,
                "rationale": "Deterministic plan derived from the explicit class creation goal.",
                "validations": ["python_ast", "python_compile"],
                "risks": [],
            }
        raise PlanningProviderError(
            "The deterministic provider accepts a structured JSON plan or "
            "'create class <Name> in <path.py>'. Select --provider ollama for free-form goals."
        )

    def generate_correction(self, goal, context, previous_plan, previous_result, failure):
        """Return a queued correction for deterministic cycle tests and automation."""

        if self._corrections:
            return self._corrections.pop(0)
        return None


class OllamaPlanningProvider:
    """Optional Ollama provider whose dependency is loaded only when used."""

    def __init__(self, model: str = "qwen2.5-coder:7b") -> None:
        self.model = model

    def generate_plan(self, goal: str, context: ProjectContext) -> Mapping[str, Any]:
        try:
            ollama = importlib.import_module("ollama")
        except ImportError as error:
            raise PlanningProviderError(
                "Ollama provider requested, but the optional 'ollama' package is not installed."
            ) from error

        prompt = self._prompt(goal, context)
        try:
            response = ollama.chat(
                model=self.model,
                messages=[{"role": "user", "content": prompt}],
                format="json",
            )
            content = self._response_content(response)
            payload = json.loads(content)
        except (AttributeError, KeyError, json.JSONDecodeError, TypeError, ValueError) as error:
            raise PlanningProviderError(f"Ollama returned an invalid structured plan: {error}") from error
        if not isinstance(payload, Mapping):
            raise PlanningProviderError("Ollama returned a JSON value that is not a plan object.")
        return payload

    def _response_content(self, response: Any) -> str:
        """Read both Ollama client's object and dictionary response shapes."""

        if isinstance(response, Mapping):
            message = response["message"]
            if isinstance(message, Mapping):
                return str(message["content"])
            return str(getattr(message, "content"))
        return str(response.message.content)

    def _prompt(self, goal: str, context: ProjectContext) -> str:
        schema = {
            "goal": goal,
            "affected_files": ["relative/path.py"],
            "operations": [
                {
                    "domain": "python",
                    "type": "create_class",
                    "parameters": {"path": "relative/path.py", "class_name": "Name"},
                    "reason": "brief reason",
                }
            ],
            "rationale": "brief rationale",
            "validations": ["python_ast", "python_compile"],
            "risks": [],
        }
        return (
            "Produce only one JSON object matching this schema. Use only project-relative paths and "
            "CMM semantic operations; do not emit shell commands.\n"
            f"Schema example: {json.dumps(schema, ensure_ascii=True)}\n"
            f"Project context: {json.dumps(context.serialize(), ensure_ascii=True)}\n"
            f"Goal: {goal}"
        )


def create_planning_provider(name: str) -> PlanningProvider:
    """Resolve a provider name from the CLI without importing optional dependencies."""

    provider_name, separator, model = name.partition(":")
    if provider_name == "deterministic":
        if separator:
            raise PlanValidationError("The deterministic provider does not accept a model suffix.")
        return DeterministicPlanningProvider()
    if provider_name == "ollama":
        return OllamaPlanningProvider(model or "qwen2.5-coder:7b")
    raise PlanValidationError(f"Unknown planning provider: {name}")
