# ── Phase 8.3 ─────────────────────────────────────────────────────────────────
from cmm.cognitive.adapters import (
    AdaptationContext,
    ExistingResourceAdapter,
    MappingResourceAdapter,
    PlainTextResourceAdapter,
    ResourceAdaptationResult,
    ResourceAdapter,
    ResourceInput,
)
from cmm.cognitive.consolidation import KnowledgeConsolidator
from cmm.cognitive.consolidation_contracts import (
    ConsolidationAction,
    ConsolidationCandidate,
    ConsolidationDecision,
    ConsolidationMatchKind,
    ConsolidationPlan,
    ConsolidationResult,
    knowledge_fingerprint,
    normalize_statement,
)
from cmm.cognitive.contracts import (
    CognitiveActor,
    CognitiveFinding,
    CognitiveResult,
    Confidence,
)
from cmm.cognitive.contradiction_detection import KnowledgeContradictionDetector
from cmm.cognitive.contradiction_detection_contracts import (
    ContradictionDetection,
    ContradictionDetectionResult,
    ContradictionKind,
    ContradictionSignal,
)
from cmm.cognitive.enums import (
    AdaptationStatus,
    CandidateKind,
    CognitiveActorKind,
    CognitiveSeverity,
    CognitiveStatus,
    ContradictionSeverity,
    ContradictionStatus,
    EvidenceKind,
    EvidencePolarityKind,
    ExtractionStatus,
    KnowledgeKind,
    KnowledgeRelationKind,
    KnowledgeStatus,
    ResourceIntegrityStatus,
    ResourceKind,
    ResourcePermissionOperation,
    ResourceSourceKind,
    SensitivityLevel,
    TemporalScopeKind,
    TemporalValidityStatus,
)
from cmm.cognitive.errors import (
    CognitiveError,
    ComponentNotCompatibleError,
    ComponentNotFoundError,
    ContradictionRegistrationError,
    DuplicateRegistryEntryError,
    InvalidAdaptationError,
    InvalidAdapterContractError,
    InvalidCognitiveContractError,
    InvalidCognitiveIdentifierError,
    InvalidConfidenceError,
    InvalidConsolidationCandidateError,
    InvalidConsolidationPlanError,
    InvalidContradictionDetectionError,
    InvalidContradictionError,
    InvalidContradictionSignalError,
    InvalidEvidenceError,
    InvalidExtractionError,
    InvalidExtractionEvidenceError,
    InvalidKnowledgeBundleError,
    InvalidKnowledgeItemError,
    InvalidKnowledgeModelError,
    InvalidKnowledgeQueryError,
    InvalidKnowledgeRelationError,
    InvalidResourceError,
    InvalidResourceInputError,
    InvalidResourcePermissionError,
    InvalidResourceProvenanceError,
    InvalidResourceTemporalScopeError,
    InvalidTemporalValidityError,
    KnowledgeConsolidationApplicationError,
    KnowledgeConsolidationConflictError,
    KnowledgeConsolidationError,
    KnowledgeContradictionConflictError,
    KnowledgeContradictionDetectionError,
    KnowledgeRetrievalError,
    KnowledgeStoreConflictError,
    KnowledgeStoreCorruptionError,
    KnowledgeStoreError,
    KnowledgeStoreNotFoundError,
    KnowledgeStoreSchemaError,
    KnowledgeStoreSerializationError,
    ManualReviewRequiredError,
    UnsupportedKnowledgeQueryError,
)
from cmm.cognitive.extraction import (
    ExtractionCandidate,
    ExtractionContext,
    ExtractionEvidence,
    KnowledgeExtractionResult,
    KnowledgeExtractor,
    MappingKnowledgeExtractor,
    PlainTextKnowledgeExtractor,
)
from cmm.cognitive.identifiers import (
    CognitiveIdentifier,
    generate_cognitive_id,
)
from cmm.cognitive.knowledge import (
    Contradiction,
    Evidence,
    KnowledgeBundle,
    KnowledgeItem,
    KnowledgeRelation,
    TemporalScope,
)
from cmm.cognitive.knowledge_materializer import (
    materialise_candidate,
    materialise_evidence,
    materialise_result,
)
from cmm.cognitive.query import (
    KnowledgeOrderField,
    KnowledgeQuery,
    KnowledgeQueryResult,
    SortDirection,
)
from cmm.cognitive.registries import (
    KnowledgeExtractorRegistry,
    ResourceAdapterRegistry,
)

# ── Phase 8.2 ─────────────────────────────────────────────────────────────────
from cmm.cognitive.resources import (
    Resource,
    ResourcePermission,
    ResourceProvenance,
    ResourceTemporalScope,
    ResourceTransformation,
)
from cmm.cognitive.retrieval import KnowledgeRetriever
from cmm.cognitive.service import (
    AdaptAndExtractResult,
    ResourceExtractionService,
)
from cmm.cognitive.store import (
    KNOWLEDGE_STORE_SCHEMA_VERSION,
    InMemoryKnowledgeStore,
    KnowledgeStoreProtocol,
    LocalKnowledgeStore,
    SQLiteKnowledgeStore,
)

__all__ = [
    # 8.5 store
    "KNOWLEDGE_STORE_SCHEMA_VERSION",
    # 8.3 service
    "AdaptAndExtractResult",
    # 8.3 adapters
    "AdaptationContext",
    # 8.3 enums
    "AdaptationStatus",
    "CandidateKind",
    # 8.1 contracts
    "CognitiveActor",
    "CognitiveActorKind",
    "CognitiveError",
    "CognitiveFinding",
    "CognitiveIdentifier",
    "CognitiveResult",
    "CognitiveSeverity",
    "CognitiveStatus",
    # 8.3 errors
    "ComponentNotCompatibleError",
    "ComponentNotFoundError",
    "Confidence",
    # 8.7 consolidation
    "ConsolidationAction",
    "ConsolidationCandidate",
    "ConsolidationDecision",
    "ConsolidationMatchKind",
    "ConsolidationPlan",
    "ConsolidationResult",
    "Contradiction",
    # 8.8 contradiction detection
    "ContradictionDetection",
    "ContradictionDetectionResult",
    "ContradictionKind",
    "ContradictionRegistrationError",
    "ContradictionSeverity",
    "ContradictionSignal",
    "ContradictionStatus",
    "DuplicateRegistryEntryError",
    "Evidence",
    "EvidenceKind",
    "EvidencePolarityKind",
    "ExistingResourceAdapter",
    # 8.3 extraction
    "ExtractionCandidate",
    "ExtractionContext",
    "ExtractionEvidence",
    "ExtractionStatus",
    "InMemoryKnowledgeStore",
    "InvalidAdaptationError",
    "InvalidAdapterContractError",
    "InvalidCognitiveContractError",
    "InvalidCognitiveIdentifierError",
    "InvalidConfidenceError",
    "InvalidConsolidationCandidateError",
    "InvalidConsolidationPlanError",
    # 8.8 errors
    "InvalidContradictionDetectionError",
    "InvalidContradictionError",
    "InvalidContradictionSignalError",
    "InvalidEvidenceError",
    "InvalidExtractionError",
    "InvalidExtractionEvidenceError",
    "InvalidKnowledgeBundleError",
    "InvalidKnowledgeItemError",
    "InvalidKnowledgeModelError",
    "InvalidKnowledgeQueryError",
    "InvalidKnowledgeRelationError",
    "InvalidResourceError",
    "InvalidResourceInputError",
    "InvalidResourcePermissionError",
    "InvalidResourceProvenanceError",
    "InvalidResourceTemporalScopeError",
    "InvalidTemporalValidityError",
    "KnowledgeBundle",
    "KnowledgeConsolidationApplicationError",
    "KnowledgeConsolidationConflictError",
    "KnowledgeConsolidationError",
    "KnowledgeConsolidator",
    "KnowledgeContradictionConflictError",
    "KnowledgeContradictionDetectionError",
    "KnowledgeContradictionDetector",
    "KnowledgeExtractionResult",
    "KnowledgeExtractor",
    # 8.3 registries
    "KnowledgeExtractorRegistry",
    "KnowledgeItem",
    "KnowledgeKind",
    "KnowledgeOrderField",
    "KnowledgeQuery",
    "KnowledgeQueryResult",
    "KnowledgeRelation",
    "KnowledgeRelationKind",
    "KnowledgeRetrievalError",
    "KnowledgeRetriever",
    "KnowledgeStatus",
    "KnowledgeStoreConflictError",
    "KnowledgeStoreCorruptionError",
    "KnowledgeStoreError",
    "KnowledgeStoreNotFoundError",
    "KnowledgeStoreProtocol",
    "KnowledgeStoreSchemaError",
    "KnowledgeStoreSerializationError",
    "LocalKnowledgeStore",
    "ManualReviewRequiredError",
    "MappingKnowledgeExtractor",
    "MappingResourceAdapter",
    "PlainTextKnowledgeExtractor",
    "PlainTextResourceAdapter",
    # 8.2 resources
    "Resource",
    "ResourceAdaptationResult",
    "ResourceAdapter",
    "ResourceAdapterRegistry",
    "ResourceExtractionService",
    "ResourceInput",
    "ResourceIntegrityStatus",
    "ResourceKind",
    "ResourcePermission",
    "ResourcePermissionOperation",
    "ResourceProvenance",
    "ResourceSourceKind",
    "ResourceTemporalScope",
    "ResourceTransformation",
    "SQLiteKnowledgeStore",
    "SensitivityLevel",
    "SortDirection",
    "TemporalScope",
    "TemporalScopeKind",
    "TemporalValidityStatus",
    "UnsupportedKnowledgeQueryError",
    "generate_cognitive_id",
    "knowledge_fingerprint",
    # 8.4 materializer
    "materialise_candidate",
    "materialise_evidence",
    "materialise_result",
    "normalize_statement",
]
