"""Phase 10.25 — Concerns Domain Profile.

A deliberately conservative ``DomainProfileDefinition`` for concern support:
high sensitivity, high epistemic discipline, high uncertainty tolerance, low
default action pressure and alarm, evidence-calibrated reassurance,
material-only questioning, willingness to state a grounded opinion,
cross-domain awareness, no automatic personal decisions, no diagnosis, no
pathologizing of recurrence, and confirmation-gated semantic persistence.

It configures shared cognition through the shared profile contracts; it does
not create a cognitive engine and never encodes a communication persona.
"""

from __future__ import annotations

from cmm.cognitive.enums import SensitivityLevel
from cmm.domains.concerns.catalog import CANONICAL_CONCERNS_RULE_IDS
from cmm.domains.concerns.resources import CONCERNS_RESOURCE_KINDS
from cmm.domains.enums import DomainReasoningDepth
from cmm.domains.profile_contracts import (
    DomainMemoryPolicy,
    DomainPresentationPolicy,
    DomainProductionPolicy,
    DomainProfileDefinition,
    DomainQuestionPolicy,
    DomainTemporalPolicy,
)

CONCERNS_PROFILE_ID = "concerns.profile"
CONCERNS_PROFILE_NAME = "ConcernSupportProfile"

# Forbidden autonomous actions of the Concerns safety model (frozen design
# §7, §71, §73, §74).  Concerns prepares; it never executes.
CONCERNS_PROHIBITED_ACTIONS: tuple[str, ...] = (
    "personal_decision_adoption",
    "decision_adoption",
    "strategy_adoption",
    "semantic_memory_write",
    "memory_persistence",
    "unconfirmed_memory_persistence",
    "fear_persistence",
    "support_need_persistence",
    "emotional_pattern_persistence",
    "recurring_pattern_persistence",
    "psychological_interpretation_persistence",
    "risk_interpretation_persistence",
    "third_party_motive_persistence",
    "diagnosis_presentation",
    "no_diagnosis_presentation",
    "psychological_diagnosis",
    "third_party_diagnosis",
    "repetition_pathologizing",
    "psychiatric_label_inference",
    "external_communication",
    "message_send",
    "email_send",
    "professional_contact",
    "appointment_booking",
    "calendar_modification",
    "task_creation",
    "schedule_modification",
    "monitoring_start",
    "content_publication",
    "purchase",
    "form_submission",
    "knowledge_delete",
    "export",
    "shell_execution",
    "sensitive_inference_persist",
)


def build_concerns_profile() -> DomainProfileDefinition:
    """Build the ``ConcernSupportProfile`` deterministically."""
    return DomainProfileDefinition(
        id=CONCERNS_PROFILE_ID,
        domain_id="domain:concerns",
        profile_name=CONCERNS_PROFILE_NAME,
        required_rules=CANONICAL_CONCERNS_RULE_IDS,
        optional_rules=(),
        prohibited_rules=(),
        allowed_resource_kinds=CONCERNS_RESOURCE_KINDS,
        priority_resource_kinds=("user_message", "conversation"),
        prohibited_resource_kinds=(),
        minimum_confidence=0.6,
        reasoning_depth=DomainReasoningDepth.STANDARD,
        allowed_inferences=(
            "observation",
            "user_stated_experience",
            "lived_experience",
            "emotion_candidate",
            "fear_as_fear",
            "interpretation",
            "hypothesis",
            "scenario_as_scenario",
            "support_need_hypothesis",
            "mixed_support_need",
            "unclear_support_need",
            "multiple_hypotheses",
            "counter_hypothesis",
            "uncertainty",
            "open_question",
            "material_question",
            "missing_information",
            "evidence_calibrated_reassurance",
            "partial_reassurance_with_uncertainty",
            "material_concern_acknowledgement",
            "grounded_opinion",
            "disagreement_with_explicit_basis",
            "proportional_risk",
            "specialized_risk_preservation",
            "action_state_without_pressure",
            "option_candidate",
            "next_step_proposal",
            "prepared_content",
            "proposal",
            "recurring_review_comparison",
            "session_state_distinction",
            "no_forced_action",
            "no_forced_closure",
        ),
        prohibited_inferences=(
            "identity_classification",
            "personality_classification",
            "mental_disorder_diagnosis",
            "psychological_diagnosis",
            "ocd_classification",
            "anxiety_disorder_classification",
            "compulsion_classification",
            "psychiatric_label_inference",
            "third_party_diagnosis",
            "moral_character_inference",
            "fixed_motive_inference",
            "repetition_pathology_inference",
            "emotional_intensity_to_risk",
            "possibility_to_probability_promotion",
            "ambiguity_to_warning_sign_promotion",
            "silence_to_rejection_inference",
            "symptom_to_serious_disease_promotion",
            "setback_to_failure_promotion",
            "uncertainty_to_danger_promotion",
            "decision_adoption",
            "personal_decision_inference",
            "external_action_execution",
            "sensitive_inference_persist",
        ),
        maximum_questions=3,
        escalation_rules=(
            "concerns.immediate_risk_escalation",
            "concerns.support_need_calibration",
            "concerns.contextual_question",
        ),
        prohibited_actions=CONCERNS_PROHIBITED_ACTIONS,
        question_policy=DomainQuestionPolicy(
            maximum_questions=3,
            allow_follow_up=True,
            require_deduplication=True,
            allow_clarification=True,
            stop_on_blocking_gap=True,
        ),
        presentation_policy=DomainPresentationPolicy(
            detail_level="detailed",
            include_uncertainty=True,
            include_provenance=True,
            include_alternatives=True,
            allow_speculation=False,
            require_disclaimers=True,
            required_sections=(
                "actual_concern",
                "lived_impact",
                "perspective",
                "epistemic_distinctions",
                "uncertainty",
                "reassurance_or_material_concern",
                "proportional_action",
            ),
            optional_sections=(
                "facts",
                "interpretations",
                "hypotheses",
                "scenarios",
                "evidence",
                "counterevidence",
                "open_questions",
                "options",
                "next_step",
                "sources",
            ),
            suppressible_sections=(),
            preferred_section_order=(
                "actual_concern",
                "lived_impact",
                "perspective",
                "epistemic_distinctions",
                "uncertainty",
                "reassurance_or_material_concern",
                "proportional_action",
            ),
            protected_terms=(
                "fact",
                "experience",
                "interpretation",
                "hypothesis",
                "fear",
                "scenario",
                "uncertainty",
                "possibility",
                "probability",
                "not_a_prediction",
                "not_a_diagnosis",
                "reassurance_supported",
                "reassurance_partial",
                "material_concern",
                "candidate_option",
                "prepared_content",
                "proposal",
            ),
            term_glosses={
                "fact": "grounded proposition with source support",
                "experience": "valid lived experience, not external proof",
                "interpretation": "assigned meaning, not an observed fact",
                "hypothesis": "unverified explanatory account",
                "fear": "feared possibility, not a prediction",
                "scenario": "possible future sequence, not a probability",
                "uncertainty": "what remains unknown or unresolved",
                "possibility": "may happen, not established as likely",
                "probability": "only from an authorized specialized source",
                "not_a_prediction": "a feared meaning is not an outcome claim",
                "not_a_diagnosis": "never a clinical or psychiatric label",
                "reassurance_supported": "calming conclusion backed by evidence",
                "reassurance_partial": "one fear is weak while another remains real",
                "material_concern": "a real problem acknowledged as such",
                "candidate_option": "an option, not an adopted decision",
                "prepared_content": "preparation only, no transmission",
                "proposal": "a candidate next step, never adopted automatically",
            },
            preferred_components=(
                "actual_concern",
                "lived_impact",
                "perspective",
                "uncertainty",
                "reassurance_or_material_concern",
            ),
            preferred_views=("structured",),
            warning_position="before_content",
            allowed_output_types=("HUMAN_READABLE", "STRUCTURED"),
            preferred_output_types=("STRUCTURED",),
        ),
        memory_policy=DomainMemoryPolicy(
            allow_read=True,
            allow_write=False,
            allow_long_term=False,
            allow_cross_domain=False,
            retention_scope="session",
            sensitivity_limit=SensitivityLevel.HIGHLY_SENSITIVE,
        ),
        temporal_policy=DomainTemporalPolicy(
            require_current_information=False,
            allow_historical_information=True,
            require_temporal_provenance=True,
            allow_future_projection=False,
        ),
        production_policy=DomainProductionPolicy(
            allow_draft=True,
            allow_final=False,
            allow_external_action=False,
            require_review=True,
            require_validation=True,
            maximum_output_items=64,
        ),
        permissions=(
            "resource.read",
            "memory.read",
            "operation.execute",
        ),
        metadata={
            "phase": "10.25",
            "contextual_sensitivity": "high",
            "epistemic_discipline": "high",
            "uncertainty_tolerance": "high",
            "emotional_context_awareness": "high",
            "interpretive_openness": "moderate_high",
            "default_action_pressure": "low",
            "default_alarm": "low",
            "reassurance_policy": "evidence_calibrated",
            "grounded_opinion_allowed": True,
            "question_policy": "material_only",
            "cross_domain_awareness": True,
        },
    )


__all__ = [
    "CONCERNS_PROFILE_ID",
    "CONCERNS_PROFILE_NAME",
    "CONCERNS_PROHIBITED_ACTIONS",
    "build_concerns_profile",
]
