"""Phase 10.30 — Permanent 34-Class Adversarial Closure Gate."""

from __future__ import annotations

PROJECT_CLOSURE_ATTACK_CLASSES = (
    "GENERIC_PROJECT_NOT_SOFTWARE_ONLY",
    "SOFTWARE_CAPABILITY_NOT_IMPLICIT",
    "FORMATION_NOT_ABSORBED",
    "UNKNOWN_PROJECT_STATUS_FAILS_CLOSED",
    "PROPOSAL_NOT_DECISION",
    "PLAN_NOT_COMPLETION",
    "MILESTONE_COMPLETION_REQUIRES_EVIDENCE",
    "MALFORMED_MILESTONE_FAILS_CLOSED",
    "DEPENDENCY_CYCLE_PRESERVED",
    "MALFORMED_DEPENDENCY_FAILS_CLOSED",
    "RESOURCE_CAPACITY_NOT_INVENTED",
    "PROGRESS_REQUIRES_EVIDENCE",
    "RAW_CROSS_DOMAIN_REJECTED",
    "FORGED_CROSS_DOMAIN_PERMISSION_REJECTED",
    "PURPOSE_MINIMIZATION_ENFORCED",
    "LEGACY_CATALOG_NOT_CANONICAL",
    "LEGACY_COLLISION_NO_SILENT_OVERWRITE",
    "OPERATION_UNAVAILABLE_WITHOUT_IMPLEMENTATION",
    "DIRECT_EXECUTION_BYPASS_REJECTED",
    "FILE_MODIFY_WITHOUT_APPROVAL_REJECTED",
    "FORGED_APPROVAL_REJECTED",
    "VALIDATION_REQUIRED_BEFORE_COMMIT_READINESS",
    "FAILED_VALIDATION_NOT_COMMIT_READY",
    "PREPARE_COMMIT_DOES_NOT_COMMIT",
    "NO_FAKE_COMMIT_REFERENCE",
    "MUTATION_REQUIRES_SHARED_ROLLBACK_PATH",
    "MEMORY_WRITE_FAILS_CLOSED",
    "MEMORY_DOES_NOT_PROMOTE_PROPOSAL",
    "MEMORY_DOES_NOT_PROMOTE_COMMIT_READINESS",
    "TRACE_IDENTITY_USES_SHARED_API",
    "TRACE_INVENTORY_INDEPENDENT",
    "TRACE_TAMPER_REJECTED",
    "ATOMIC_REGISTRATION_ROLLBACK",
    "GENERAL_FALLBACK_PRESERVED",
)


def test_frozen_attack_inventory_is_exact() -> None:
    assert len(PROJECT_CLOSURE_ATTACK_CLASSES) == 34
    assert len(set(PROJECT_CLOSURE_ATTACK_CLASSES)) == 34
