"""Language-agnostic transformation framework for CMM OS."""

from cmm.transformations.adapter import TransformationActionAdapter
from cmm.transformations.basic_executor import BasicTransformationExecutor
from cmm.transformations.basic_planner import BasicTransformationPlanner
from cmm.transformations.dispatcher import TransformationDispatcher
from cmm.transformations.execution_request import ExecutionRequest
from cmm.transformations.execution_plan import ExecutionPlan
from cmm.transformations.execution_planner import ExecutionPlanner
from cmm.transformations.execution_stage import ExecutionStage
from cmm.transformations.executor import TransformationExecutor
from cmm.transformations.graph import (
    GraphValidationError,
    GraphValidationResult,
    TransformationGraph,
)
from cmm.transformations.models import TransformationGraphNode, TransformationStep
from cmm.transformations.move_class import MoveClassTransformation
from cmm.transformations.move_function import (
    MoveFunctionTransformation,
    MoveFunctionTransformationBuilder,
)
from cmm.transformations.extract_method import ExtractMethodTransformation
from cmm.transformations.extract_module import ExtractModuleTransformation
from cmm.transformations.reorganization import (
    MergeModulesTransformation,
    MoveModuleTransformation,
    MovePackageTransformation,
    RenameModuleTransformation,
    RenamePackageTransformation,
    SplitModuleTransformation,
)
from cmm.transformations.operation import TransformationOperation
from cmm.transformations.operations import (
    CopySymbolOperation,
    CreateFileOperation,
    CreateModuleOperation,
    DeleteFileOperation,
    DeleteModuleOperation,
    DeleteSymbolOperation,
    ExtractMethodOperation,
    ExtractModuleOperation,
    MoveSymbolOperation,
    RenameSymbolOperation,
    UpdateImportsOperation,
    ValidateProjectOperation,
    MergeModulesOperation,
    MoveModuleOperation,
    MovePackageOperation,
    RenameModuleOperation,
    RenamePackageOperation,
    ReorganizationOperation,
    SplitModuleGroup,
    SplitModuleOperation,
)
from cmm.transformations.plan import TransformationPlan
from cmm.transformations.preconditions import (
    FileExistsPrecondition,
    FunctionDependenciesPrecondition,
    ModuleExistsPrecondition,
    PreconditionResult,
    SymbolAbsentPrecondition,
    SymbolExistsPrecondition,
    SupportedSymbolReferencesPrecondition,
    SymbolDependenciesPrecondition,
    ExtractMethodPrecondition,
    ExtractModulePrecondition,
    ImpactAnalysisPrecondition,
    ReorganizationPrecondition,
    TransformationPrecondition,
)
from cmm.transformations.planner import TransformationPlanner
from cmm.transformations.registry import (
    OperationRegistry,
    TransformationRegistry,
    UnsupportedOperationError,
    UnsupportedTransformationError,
)
from cmm.transformations.transformation import Transformation
from cmm.transformations.symbol_kind import SymbolKind, SUPPORTED_SYMBOL_KINDS
from cmm.transformations.impact_analysis import (
    DependencyEdge,
    ImpactAnalysisRequest,
    ImpactAnalysisResult,
    ImpactAnalyzer,
    ImpactDiscrepancy,
    ImpactDiscrepancyCode,
    ImpactedModule,
    ImpactedSymbol,
    ImpactIssue,
    ImpactIssueCode,
    ImpactSeverity,
    ImportReference,
    ExpectedImpactPlan,
    PostImpactValidationResult,
    ProjectReferenceGraph,
    ReferenceKind,
    ReferenceLocation,
    RewriteCapability,
    SymbolReference,
)

__all__ = [
    "BasicTransformationExecutor",
    "BasicTransformationPlanner",
    "CopySymbolOperation",
    "CreateFileOperation",
    "CreateModuleOperation",
    "DeleteFileOperation",
    "DeleteModuleOperation",
    "DeleteSymbolOperation",
    "ExtractMethodOperation",
    "ExtractModuleOperation",
    "ExecutionRequest",
    "ExecutionPlan",
    "ExecutionPlanner",
    "ExecutionStage",
    "ExtractMethodTransformation",
    "ExtractModuleTransformation",
    "FileExistsPrecondition",
    "FunctionDependenciesPrecondition",
    "GraphValidationError",
    "GraphValidationResult",
    "MoveSymbolOperation",
    "MoveClassTransformation",
    "MoveFunctionTransformation",
    "MoveFunctionTransformationBuilder",
    "OperationRegistry",
    "RenameSymbolOperation",
    "Transformation",
    "SymbolKind",
    "SUPPORTED_SYMBOL_KINDS",
    "TransformationActionAdapter",
    "TransformationOperation",
    "TransformationDispatcher",
    "TransformationExecutor",
    "TransformationGraph",
    "TransformationGraphNode",
    "TransformationPlan",
    "ModuleExistsPrecondition",
    "PreconditionResult",
    "TransformationPlanner",
    "TransformationRegistry",
    "TransformationStep",
    "SymbolExistsPrecondition",
    "SymbolAbsentPrecondition",
    "SupportedSymbolReferencesPrecondition",
    "SymbolDependenciesPrecondition",
    "ExtractMethodPrecondition",
    "ExtractModulePrecondition",
    "TransformationPrecondition",
    "UnsupportedOperationError",
    "UnsupportedTransformationError",
    "UpdateImportsOperation",
    "ValidateProjectOperation",
    "MergeModulesOperation",
    "MoveModuleOperation",
    "MovePackageOperation",
    "RenameModuleOperation",
    "RenamePackageOperation",
    "ReorganizationOperation",
    "SplitModuleGroup",
    "SplitModuleOperation",
    "MergeModulesTransformation",
    "MoveModuleTransformation",
    "MovePackageTransformation",
    "RenameModuleTransformation",
    "RenamePackageTransformation",
    "SplitModuleTransformation",
    "DependencyEdge",
    "ImpactAnalysisPrecondition",
    "ReorganizationPrecondition",
    "ImpactAnalysisRequest",
    "ImpactAnalysisResult",
    "ImpactAnalyzer",
    "ImpactDiscrepancy",
    "ImpactDiscrepancyCode",
    "ImpactedModule",
    "ImpactedSymbol",
    "ImpactIssue",
    "ImpactIssueCode",
    "ImpactSeverity",
    "ImportReference",
    "ExpectedImpactPlan",
    "PostImpactValidationResult",
    "ProjectReferenceGraph",
    "ReferenceKind",
    "ReferenceLocation",
    "RewriteCapability",
    "SymbolReference",
]
